### ISSUE TITLE
[Feature request] Possibility to assign other key combinations (allow to use ctrl as super)

### ISSUE THREAD

**Issue by danieltomasz** [vslinko/obsidian-outliner#1]
Great extension to Obsidian!
I really like the CSS for Outliner!

I have a request  for the future - I didn't install the addon yet but I saw the Pull request discussion on the Obsidian repository:
You use the combinations:
```
Cmd-ArrowUp, Cmd-ArrowDown - Expand / collapse.
Cmd-Shift-ArrowUp, Cmd-Shift-ArrowDown, - Move item and subitems.
```
I am on Linux (PopOS) and those combinations are used by my window manager to move between windows and workspaces  
On the other hand, I have a Ctrl key that is available for those combinations.

I am wondering how many users may have similar problems where the windows/cmd key combinations are used by their window manager (this is especially popular for users of tiling managers)

If the keys will not be hardcoded then there will be no problem, but even if not  I wonder how hard would be to implement the possibility of allowing the user to replace the role of the super(cmd) key by ctrl from the level of settings.

EDIT: ok, CodeMirror ignores the ctrl, so this may be problematic :P 
https://github.com/manogna4/obsidian-koncham-undefault-hotkeys

**Comment by Quorafind** [comment]
By the way, in Windows, `Ctrl+Shift+Uparrow` is to select one line.

**Comment by vslinko** [comment]
Thank you for your comments! Yes, I forgot about other OS :) Will add `ctrl` support asap.

**Comment by vslinko** [comment]
@danieltomasz @Quorafind Could you test `ctrl` support on your OSes? I have only MacOS right not.
https://github.com/vslinko/obsidian-outliner/releases/tag/1.0.3-pre1

**Comment by Quorafind** [comment]
@vslinko It works on Win10 now. Thanks for your hard job.

**Comment by vslinko** [comment]
Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.0.3
Thank you all for contribution!

**Comment by danieltomasz** [comment]
Hi @vslinko  thanks for your hard work! The  `ctrl` works for me!

 You may want to document this behaviour in the readme later.

**Comment by vslinko** [comment]
@danieltomasz Added to README :)

**Comment by danieltomasz** [comment]
@vslinko  I think your plugin will be really popular, you may want to add in the future issues templates for [feature request] and [bug], you may want to look into it as example https://github.com/Braweria/Spectrum/tree/main/.github/ISSUE_TEMPLATE , it may save your time in the long run

**Comment by vslinko** [comment]
@danieltomasz Thank you! Copied those templates :)
