### ISSUE TITLE
Support header / subheader outlining

### ISSUE THREAD

**Issue by classicrob** [vslinko/obsidian-outliner#10]
**Is your feature request related to a problem? Please describe.**
In Obsidian, a more meaningful way to outline is with headers and subheaders. All content under a header until another header at the same or higher level is considered nested

**Describe the solution you'd like**
I would like to use the same sorts of keyboard shortcuts to manipulate headers and their nested content as "items and subitems"

**Describe alternatives you've considered**
Obsidian doesn't really have a way to do it!

**Additional context**

Let's say I decide that Chapter 2 should actually be Chapter 1. Right now, the best way to do it is just cut and paste. "Swap line up" doesn't exactly work.

![image](https://user-images.githubusercontent.com/46608303/112648186-df2eba80-8e0e-11eb-928e-08b449b539dc.png)

**Comment by vslinko** [comment]
@classicrob Thank you for your request! I can understand the use case but I think it's not exactly related to Workflowy-like experience that I want to implement.

I think it's better to create another plugin like "Move heading with it's content through the document". What do you think?

**Comment by danieltomasz** [comment]
Yes, this request is more suited  for another plugin,  "Microsoft Word" or "OneNote" style plugin 
https://forum.obsidian.md/t/navigate-move-indent-and-unindent-by-heading/4202/10

**Comment by classicrob** [comment]
> @classicrob Thank you for your request! I can understand the use case but I think it's not exactly related to Workflowy-like experience that I want to implement.
> 
> I think it's better to create another plugin like "Move heading with it's content through the document". What do you think?

A separate plugin would be fine! Would you make it, or should I post a plugin request? I view outlining with headings and subheadings as very similar in spirit to bullet point oriented outlining (at least they are treated this way in org-mode), though it seems we differ in opinion here.

**Comment by vslinko** [comment]
I could make such plugin, but I can't promise.
As I [mentioned in Discord](https://discordapp.com/channels/686053708261228577/707816848615407697/825299153059577876), I think https://github.com/manogna4/obsidian-koncham-nav-note is better place for such functionality.

**Comment by manogna4** [comment]
> > @classicrob Thank you for your request! I can understand the use case but I think it's not exactly related to Workflowy-like experience that I want to implement.
> > I think it's better to create another plugin like "Move heading with it's content through the document". What do you think?
> 
> A separate plugin would be fine! Would you make it, or should I post a plugin request? I view outlining with headings and subheadings as very similar in spirit to bullet point oriented outlining (at least they are treated this way in org-mode), though it seems we differ in opinion here.

as @vslinko has mentioned, this is definitely in my plans for [koncham-nav-note](https://github.com/manogna4/obsidian-koncham-nav-note). I can't promise when it'll happen though.

I use headers similar to you in some notes, so I've felt the need. It's not a pressing need though, so I can't promise when I'll do that.
