### ISSUE TITLE
[BUG] unfold automatically in vim mode

### ISSUE THREAD

**Issue by Palvehelmed** [vslinko/obsidian-outliner#106]
Hi there and appreciate for all your efforts! 

I have seen a bug-like apperence, when I move down cursor in Vim mode from a fold line, it unfold automatically sometimes according cursor position or just to expand with no condition. So I have to move the cursor with mouse to prevent it unfold.

It's often apperence so just open the vim mode could reporduce this behavior.

 - System: MacOS 11.2.3
 - Obsidian Version: 11.13 the latest version right now.

**Comment by vslinko** [comment]
@Palvehelmed Thank you for your contribution!

This is known issue, but this issue is in Obsidian itself. https://github.com/vslinko/obsidian-outliner/issues/67#issuecomment-817144625

Please report it to Obsidian developers.

Closing the issue.
