### ISSUE TITLE
[FEAT] Zoom in/focus on bullets

### ISSUE THREAD

**Issue by jjsteffen3d** [vslinko/obsidian-outliner#11]
**Is your feature request related to a problem? Please describe.**
Large textfiles with many lines can make it difficult to focus on one thing at a time.

**Describe the solution you'd like**
It would be awesome to zoom in on bullets/lines, similar to how it's done in workflowy with ALT+Right.

**Describe alternatives you've considered**
Manually collapsing other headers/items of a list, but that's a tedious process and slows down the outlining experience.

**Additional context**
It might be difficult or even impossible to implement a true workflowy-like experience in codemirror, but maybe there's some way to hide all lines except for the current line and its children. 
When new lines are added in "zoomed in mode", they would need to be inserted at the correct position in the actual file.
There's probably more problems I can't think of right now, but I wanted to hear your and others opinion on this, does anyone else think it's useful and/or possible?

Also, thank you so much for making this awesome extension! 
I actually started working on the exact same thing because I love workflowy a lot, but I never did any webdev or typescript before, so progress was really slow and chaotic :')

**Comment by vslinko** [comment]
@jjsteffen3d Thank you for your contribution! Released in https://github.com/vslinko/obsidian-outliner/releases/tag/1.0.6

Default hotkeys:
`Cmd-.` — Zoom-in
`Cmd-Shift-.` — Zoom-out

![](https://raw.githubusercontent.com/vslinko/obsidian-outliner/main/demo2.gif)
