### ISSUE TITLE
Enhance the Enter key: Cursor in parent item splits item

### ISSUE THREAD

**Issue by rbanks88** [vslinko/obsidian-outliner#110]
When the cursor's in a Parent Item, pressing Enter splits the paragraph at that point, instead of creating a new line on the child level. Everything else in Outliner works great, so thanks!

**To Reproduce**
1. Create a parent item with two children
2. Put cursor in parent item 
2. Hit Return

On my system (Mac Catalina) it splits the line.

**Expected behavior**
Expected it to create a new line on the child level.

**Desktop (please complete the following information):**
 - OS: Mac Catalina
 - Obsidian Version: 0.11.13

**Additional context**
Since everything else appears to work, it may be something with my system. I've created a Keyboard Maestro macro for a temporary fix, which first goes to the end of the paragraph when you hit Return. 

P.S. One other thing... Your default hotkeys for Move list and sublists up/down are Sh Cmd ↑ and ↓. However, those are default Mac shortcuts that select text from the cursor position to start or end of the document, and that's what they did for me. So, I changed them to my Hyperkey: Ctrl Opt Sh Cmd ↑ and ↓ and it worked fine.

**Comment by vslinko** [comment]
@rbanks88 Hello!

If I understood correctly is not bug, it's feature.

I recorded the behaviour, please check that it is what are you meant.
![out](https://user-images.githubusercontent.com/205823/116823989-63075f80-ab90-11eb-80cf-8108b8e512d2.gif)

Please close the bug If my answer was enough.

**Comment by rbanks88** [comment]
I guess your feature is my "bug" :)

When writing, you normally expect return to split a line, but when I'm outlining, the idea is to easily start new outline items. The dedicated app, OmniOutliner, can be set in preferences to start a new outline "row" when you hit Return. To break up an item, you hit Ctrl-Return. It would be great to have a setting to allow either behavior: split the line or start a new line.

Anyway thanks for your great, talented work! I'll close the item now.

Best,
Russell

**Comment by vslinko** [comment]
@rbanks88 I think it's possible to create such setting. Please create a discussion about this idea https://github.com/vslinko/obsidian-outliner/discussions
