### ISSUE TITLE
README.md: Not clear whether TAB to indent supports multiple bullets

### ISSUE THREAD

**Issue by thomasvs** [vslinko/obsidian-outliner#115]
From my experimentation it doesn't, although that seems like it's reasonable to expect that to work.  If it's not supported, mentioning that in README.md would be good.  In that case, I'll file a feature request to support multiple bullets.

Example use case: I have a flat bullet point list of highlights from a kindle book, and I'm trying to organize them in a hierarchical structure.

**Comment by vslinko** [comment]
@thomasvs Thank you for your idea!

Added info about unsupported features with links to the issues.

**Comment by vslinko** [comment]
https://github.com/vslinko/obsidian-outliner#unsupported-yet-features
