### ISSUE TITLE
[BUG] Unable to "select all" in file name area or search area. disabling works

### ISSUE THREAD

**Issue by rlam3** [vslinko/obsidian-outliner#116]
**Describe the bug**
Unable to "select all" in file name area or search area. disabling this works

**To Reproduce**
Unable to "select all" in file name area or search area. disabling this works

**Expected behavior**
select all and editing the text fields are allowed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Obsidian Version: latest

**Comment by vslinko** [comment]
@rlam3 Thank you for your contribution!

This is known issue, please see #90 
Closing this as a duplicate
