### ISSUE TITLE
Undoing requires 2 clicks to truly undo something.

### ISSUE THREAD

**Issue by apotenza92** [vslinko/obsidian-outliner#120]
First undo press just completely deletes whatever line was being worked on, with the second press going to the original state.
Expected behaviour is to be able to undo once and return to the previous state.

**Comment by vslinko** [comment]
@apotenza92 Thank you for your contribution!

I'll fix it after #38

**Comment by vslinko** [comment]
@apotenza92 Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.1.10
