### ISSUE TITLE
[FEAT] Dedent list items that are zoomed in on

### ISSUE THREAD

**Issue by ivan-lednev** [vslinko/obsidian-outliner#121]
E.g. this is how Logseq handles this:
![dedent-zoomed-in-list-items](https://user-images.githubusercontent.com/41428836/117281232-b95ff100-ae63-11eb-9aad-6f17eea99ef5.gif)

obsidian-outliner leaves the list item indented at the same level, which might be inconvenient for deeply indented list items.

**Comment by vslinko** [comment]
@ivan-lednev Thank you for your idea!

This idea already have their own discussion https://github.com/vslinko/obsidian-outliner/discussions/54
Please follow the discussion to stay notified about the progress.

Closing this issue as the duplicate.
