### ISSUE TITLE
[BUG] Cursor position is absolute when indenting/dedenting list items

### ISSUE THREAD

**Issue by ivan-lednev** [vslinko/obsidian-outliner#122]
When a list item is indented, the cursor should stay in the same position relative to the text, instead, only the text gets indented and the cursor stays in the same spot

1. Create a note with at least 1 indented list item
2. Place the cursor in the middle of the line
2. Press `Tab`

**Expected behavior**
The text gets indented, the cursor stays in the same spot relative to the text

**Actual behavior**
![cursor-doesnt-stay-with-text](https://user-images.githubusercontent.com/41428836/117283603-3be9b000-ae66-11eb-9893-8fc72c410ab4.gif)

**Desktop:**
 - OS: Windows
 - Obsidian Version: 0.12.2

**Comment by vslinko** [comment]
@ivan-lednev Thank you for your contribution!

Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.1.7
