### ISSUE TITLE
[BUG] CSS snippet  in default theme -  bullet per * is misaligned

### ISSUE THREAD

**Issue by danieltomasz** [vslinko/obsidian-outliner#13]
**Describe the bug**

I am using the default theme. The bullet point per * is misaligned. The bullet point per - works well

**To Reproduce**
- Use `*` to make bullet point

**Expected behavior**
Bullet point dot will overlay '*' completely
**Screenshots**

<img width="329" alt="image" src="https://user-images.githubusercontent.com/7980381/112718306-66a12a00-8ef2-11eb-87b8-ed9e5a000158.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS Big Sur/Linux
 - Obsidian Version: [e.g. 22] 0.11.9

**Additional context**
I think this problem started after update to Obsidian 0.11.9

**Comment by vslinko** [comment]
@danieltomasz Thank you for your contribution! Should be fixed in `main` branch.
https://github.com/vslinko/obsidian-outliner/blob/main/snippet.css
