### ISSUE TITLE
Can this be made to work on mobile

### ISSUE THREAD

**Issue by RoquitoPepper** [vslinko/obsidian-outliner#130]
Hi,

I love this plugin, but I can’t install it on the new mobile version of Obsidian - I get a message saying that it cannot be installed on my platform. Will this plugin work on the iOS version? If so, can this be enabled?

Many thanks

**Comment by vslinko** [comment]
@RoquitoPepper Hi! Thank you for your contribution!

Obsidian Mobile is unsupported yet. Please follow https://github.com/vslinko/obsidian-outliner/discussions/124 for more information.
