### ISSUE TITLE
[BUG] indenting a middle item of an outline causes duplication of text

### ISSUE THREAD

**Issue by cuongdo** [vslinko/obsidian-outliner#133]
**Describe the bug**
When you indent an item that's in the middle of an Obsidian list, the outliner plugin duplicates some characters at the end of the item. This is with version 1.1.10.

**To Reproduce**
1. Paste this into an Obsidian document:
```
- first item
- second item
- third item
```
2. Go to the line `second item`
3. Press `tab`
4. Notice that `second item` has changed to `second itemm`

**Expected behavior**
I expect `second item` to be indented with no changes to the text.

**Screenshots**
before indenting:
![image](https://user-images.githubusercontent.com/1564582/118498202-c4344480-b6f3-11eb-87b1-99552128ecf4.png)

after indenting:
![image](https://user-images.githubusercontent.com/1564582/118498223-cc8c7f80-b6f3-11eb-9d6d-69a5652aa262.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Obsidian Version: v0.12.3
 - Outliner plugin version: v1.1.10

**Comment by vslinko** [comment]
@cuongdo Hi! Thank you for your contribution!

Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.1.11
