### ISSUE TITLE
[BUG] - Folded lists get unfloded when pressing the backspace key somewhere else

### ISSUE THREAD

**Issue by zzdcgg** [vslinko/obsidian-outliner#137]
**Describe the bug**
A list is folded.  When pressing the backspace key somewhere else on the page, the folded list will become unfolded.

**To Reproduce**
1. Fold one list
2. Press the backspace key somewhere else
3. The folded list will automatically become unfolded even though nothing was done specifically to the list previously folded.

**Expected behavior**
The folded list stays as it is.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [MacOS
 - Obsidian Version: [0.12.3]

**Comment by vslinko** [comment]
@zzdcgg Thank you for your contribution!

Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.1.12

**Comment by zzdcgg** [comment]
Yes it is working now. Thanks!
