### ISSUE TITLE
[BUG] List indent

### ISSUE THREAD

**Issue by joshsvnd** [vslinko/obsidian-outliner#139]
**Describe the bug**
When tabbing and shift-tabbing and indented list the contents of the list gets copied and doubles each time this occurs. All other community plug-ins have been disabled. 

 **To Reproduce**
This hasn't reproduced in another vault and though continues after restarting obsidian. Only seems to be for this particular list. 

**Expected behavior**
List parent and child indent. 

**Screenshots**
![Screen Shot 2021-05-20 at 11 10 32 am](https://user-images.githubusercontent.com/48191498/118903888-01027480-b95c-11eb-8364-ff50a8c75a67.png)

**Desktop (please complete the following information):**
 - OS: MAC OS Big Sur
 - Obsidian Version: 0.12.3

**Additional context**
![possible_outliner_bug](https://user-images.githubusercontent.com/48191498/118906477-38275480-b961-11eb-8a75-a67f8563bd7c.gif)

**Comment by vslinko** [comment]
@joshsvnd Hi! Please try to update the plugin. It should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.1.11

**Comment by joshsvnd** [comment]
🤦‍♂️  I should have checked that. Thanks. That seems to have fixed it.
