### ISSUE TITLE
[BUG] Outdenting does not always work in 1.2 release

### ISSUE THREAD

**Issue by danieltomasz** [vslinko/obsidian-outliner#144]
**Describe the bug**
Outdenting does not always work/

**To Reproduce**
I observed weird behaviour, I have this in outline in my vault(I removed some personal notes, but the structure of the outline is the same), I cannot outdent the last bullet points (I am using Outliner 1.2)
```
- Thinking in Systems
	-  Line 1
		- LIne 2
	- Line 3
	- Nie m liniowych systemow
		
	- Random link from Internet
		[Swasthi's Recipes - Indian food blog with easy Indian recipes](https://www.indianhealthyrecipes.com/)
	- Cannot move this line with Tab + Shift
```

When I start outdenting with Shift + Tab from `Line 1`  everything start working again, and I can out dent the other lines too

**Desktop (please complete the following information):**
 - Obsidian Version: [e.g. 22] 0.12.3

**Additional context**

**Comment by vslinko** [comment]
@danieltomasz Thank you for your contribution!

Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.2.1

**Comment by danieltomasz** [comment]
hanks! @vslinko  I am really impressed with how fast you are fixing bugs and introducing new features!
