### ISSUE TITLE
[BUG] Bullet structure breaks after creating a second separate list

### ISSUE THREAD

**Issue by Ivcota** [vslinko/obsidian-outliner#155]
**Describe the bug**
The bullet structure breaks after creating 2 separate lists on the same document.

**To Reproduce**
1. Open a new document.
2. Create 2 lists
3. The first list will work correctly when you indent and create children and sibling bullets
4. The second list will not maintain structure when trying to organize the bullets.

**Expected behavior**
Separate lists should be able to work under the same document with the same structure and constraints.

**Screenshots/Videos**

https://user-images.githubusercontent.com/18635074/120082396-aa8de800-c077-11eb-851e-cdd6cba04639.mp4

**Desktop:**
 - OS: Windows 10
 - Obsidian Version: v.0.12.4

**Comment by knotha** [comment]
When I have two separate lists in one file (accidentally by making an empty line in the middle of my list), I observed that sub-lists or bullets no longer can be moved up and down with Ctrl + Shift + Up/Down arrows. Functionality is restored by removing the empty line and connecting the lists into one.

Thank you for a great plugin!
Gustav

**Comment by vslinko** [comment]
@Ivcota @knotha Thank you for your contributions! Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.2.4
