### ISSUE TITLE
[BUG] Pressing enter at the start of a line creates an unwanted bullet point

### ISSUE THREAD

**Issue by OliverBalfour** [vslinko/obsidian-outliner#156]
**Describe the bug**
If you press enter at the start of a line with a bullet item, a new bullet is created with messed up content.

**To Reproduce**
1. Create a bullet point list
2. Move the cursor to the start of a line before the bullet point
3. Press Enter

**Expected behavior**
I would have expected pressing enter at the start of the line to add a blank line above the cursor.

**Screenshots**
Here's a short screen recording:
https://user-images.githubusercontent.com/11626018/120585635-6d5d9780-c475-11eb-853c-957dee7e7b28.mp4

**Desktop**
 - OS: Arch Linux
 - Obsidian Version: 0.12.4

**Comment by vslinko** [comment]
@OliverBalfour Hi! Do you have the "Stick the cursor to the content" setting turned off?

**Comment by OliverBalfour** [comment]
Yes, I do. I had this disabled from memory because of some issues when it was on.

I can't remember all of the specifics, but one thing that stands out is when it's enabled, pressing left at the start of the first bullet in a list doesn't go to the previous line like it does without outliner, it just stays stuck at the start of the list

**Comment by vslinko** [comment]
@OliverBalfour Thank you for your contribution! Problems with Enter behavior and cursor movement should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.2.5

**Comment by OliverBalfour** [comment]
Wonderful, thank you!
