### ISSUE TITLE
[BUG] Showing the status bar error when using 4-spaces tabs off

### ISSUE THREAD

**Issue by GitMurf** [vslinko/obsidian-outliner#157]
This "bug" seems to be created from a change that was made in response to #143 

With the new update for Outliner plugin v1.2.5 I am getting this error saying Outliner only works with four-space tabs. I do have it set to 4 spaces, and I have tabs turned off (uses 4 spaces).

![image](https://user-images.githubusercontent.com/64155612/121109367-475f2c80-c7c0-11eb-9e07-c37d5b0f3cdf.png)

Here are my settings:

![image](https://user-images.githubusercontent.com/64155612/121109389-51812b00-c7c0-11eb-9ec8-d6bd1a7a50c5.png)

**Comment by GitMurf** [comment]
It seems @vslinko in that other issue you are maybe intending to show this error if you have tabs turned off (using spaces instead) even if you are using 4 spaces? This would be very unfortunate because then are you saying Outliner plugin only supports using Tabs? That is a deal breaker for a lot of people like me who choose to use spaces instead of Tabs in all their documents/notes.

Did I read it correctly that the only reason you warn about tabs turned off and using 4 spaces is because the indent level lines don't work? That is an obsidian core thing... the way the HTML is styled they do not have a separate HTML element for each indent (tab) so when using spaces you cannot style the indent level lines (which is fine). At minimum I'd suggest being able to turn this warning off otherwise users will likely no use the plugin if they have to see the red error all the time in their status bar.

Thanks for all your hard work and I look forward to hearing your response!

**Comment by vslinko** [comment]
@GitMurf Hi!

This warning only applies to Outliner **styles**, not to manipulation of lists. You can hide this warning by disabling "Improve the style of your lists".

Alternatively, I could add a setting like "Hide Obsidian styles warning". What do you think about this?

**Comment by GitMurf** [comment]
Yes adding the setting to "hide obsidian styles warning" would be good because it actually works great with 4 spaces and tabs turned off. Everything in the outliner works as expected including the "Improve the style of your lists". I want to use that feature but not if I have to have the red warning in the status bar all the time ;) Thanks!

**Comment by GitMurf** [comment]
Personally I think the warning is unnecessary when using 4 spaces and tabs turned off. For me everything works/looks fine with the "improve the styles of your lists".

**Comment by vslinko** [comment]
@GitMurf Thank you for your contribution! The setting should work in https://github.com/vslinko/obsidian-outliner/releases/tag/1.2.7
