### ISSUE TITLE
输入法输入中文回车时候的问题

### ISSUE THREAD

**Issue by wuqiyin** [vslinko/obsidian-outliner#158]
步骤1，输入内容：
![1](https://user-images.githubusercontent.com/26370779/121307913-12bfb200-c933-11eb-962c-9ecd77e7f607.png)

步骤2，回车，这个时候正常应该是直接输入英文字母的，但是却是下图的样子：
![2](https://user-images.githubusercontent.com/26370779/121308049-2ff48080-c933-11eb-8243-3d2f70fcd494.png)

**Comment by vslinko** [comment]
@wuqiyin Thank you for your contribution! Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.2.6
