### ISSUE TITLE
[BUG] Microsoft Wubi IME (A Chinese IME) appear a bug in a list when using Enter key to clear the input code

### ISSUE THREAD

**Issue by HaujetZhao** [vslinko/obsidian-outliner#159]
[Microsoft Wubi IME (A Chinese IME) appear a bug in a list when using Enter key to clear the input code](https://forum.obsidian.md/t/microsoft-wubi-ime-a-chinese-ime-appear-a-bug-in-a-list-when-using-enter-key-to-clear-the-input-code/19623)

### Steps to reproduce

This is hard to explain, because it concerned with a Chinese IME. To reproduce it, you may need to enable the Wubi IME (五笔输入法) :

- Go to windows **Settings App**
- **Time & Language**
- **Language**
- **Add a language** and choose **Chinese (Simplified, China)**
- In to the **Option** of **Chinese (Simplified, China)**
- **Add a keyboard**
- add **Microsoft Wubi**
- Into the **Option** of **Microsoft Wubi**
- Set the **Enter Key** selection list to **Clear Wubi coding**

Open Obsidian editor, switch to **Microsoft Wubi** IME: 

- type in `a` then `Space Key`, the `工` will appear in the editor
- type in `a` then `Enter Key`, the `a` code will be cleared

So far, everything is normal. 

Then you create a list, like: 

```markdown
- 123
- 456
```

and put the cursor into the list. Type in `a` then `Enter Key`

### Expected result

The Wubi code `a` should be cleared, and the cursor stay at where it was. 

### Actual result

The `a` code is not cleared, but saved in the editor, and the cursor moved to the next line!

Of course you can use other Wubi codes, they end the same. 

### Environment

-   Operating system: Windows 10

-   Obsidian version: 0.12.4

---

### Additional information](<### Steps to reproduce

This is hard to explain, because it concerned with a Chinese IME. To reproduce it, you need to enable the Wubi IME (五笔输入法)  in Windows 10:

- Go to windows **Settings App**
- **Time & Language**
- **Language**
- **Add a language** and choose **Chinese (Simplified, China)**
- In to the **Option** of **Chinese (Simplified, China)**
- **Add a keyboard**
- add **Microsoft Wubi**
- Into the **Option** of **Microsoft Wubi**
- Set the **Enter Key** selection list to **Clear Wubi coding**

Open Obsidian editor, switch to **Microsoft Wubi** IME: 

- type in `a` then `Space Key`, the `工` will appear in the editor
- type in `a` then `Enter Key`, the `a` code will be cleared

So far, everything is normal. 

Then you create a list, like: 

```markdown
- 123
- 456
```

and put the cursor into the list. Type in `a` then `Enter Key`

### Expected result

The Wubi code `a` should be cleared, and the cursor stay at where it was. 

### Actual result

The `a` code is not cleared, but saved in the editor, and the cursor moved to the next line!

Of course you can use other Wubi codes, they end the same. 

### Environment

-   Operating system: Windows 10

-   Obsidian version: 0.12.4

---

### Additional information

**Comment by HaujetZhao** [comment]
Found out it is caused by the `Enhance the Enter Key` feature.

**Comment by vslinko** [comment]
@HaujetZhao Thank you for your contribution! Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.2.6
