### ISSUE TITLE
[BUG] Plugin CTRL +A , CTRL+., CTRL +SHIFT. works in Obsidian help vault but not with my note vault

### ISSUE THREAD

**Issue by danieltomasz** [vslinko/obsidian-outliner#16]
**Describe the bug**
Plugin CTRL +A , CTRL+., CTRL +SHIFT. works in Obsidian help vault but not with my note vault

**To Reproduce**
Open Obsidian help vault.
Install Outliner Plugin and turn on.
Make a list.

- A
	-  B
		-   C

Placing cursor around any item, CTRL+A will  work

Doing the same thing in  my Notes Vault lselect whole note instead of line or whole outline.
CTRL . and CTR+SHIFT+. work in Obsidian Help Vault but not in my notes vaules.
I disabled all other plugin when testing.

**Expected behavior**
Shortcuts will have consistent behaviour and will not be buggy

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux OS
 - Obsidian Version: [e.g. 22] 0.11.9

**Additional context**

**Comment by danieltomasz** [comment]
Tomorrow I will try to check output of the debug console

**Comment by vslinko** [comment]
Is it possible that your lists prefixed with `*` sign, not `-` sign?

Currently `-` is only supported.

**Comment by danieltomasz** [comment]
Yes, it was the case! Could you make it more explicit in the README?

**Comment by vslinko** [comment]
@danieltomasz It's better to support spaces :)
Released in https://github.com/vslinko/obsidian-outliner/releases/tag/1.0.10

**Comment by danieltomasz** [comment]
The speed of development astonishes me! Thanks for your hard work!
