### ISSUE TITLE
[BUG] Unable to select hyphen at the beginning of a list item

### ISSUE THREAD

**Issue by nathan-sain** [vslinko/obsidian-outliner#160]
**Describe the bug**
Unable to select hyphen at the beginning of a list item

**To Reproduce**
1. Create list '- thing one'
2. Hold shift and use arrows to highlight or use mod-A to select line
3. Hyphen is not selected and cut commands will only remove the list content without hyphen

**Expected behavior**
Hyphen is selected when using mod-A

**Screenshots**
![Screenshot - 6_15_21 , 1_00_19 PM](https://user-images.githubusercontent.com/6025214/122101261-b26cbc80-cdd9-11eb-9b52-40a045be9089.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version: v0.12.4

**Additional context**
None

**Comment by vslinko** [comment]
Hi @nathan-sain !

This is not a bug, but [the feature](https://github.com/vslinko/obsidian-outliner#stick-the-cursor-to-the-content).
You can disable it by turning off the "Stick the cursor to the content" setting.

**Comment by nathan-sain** [comment]
Oh! Sorry, thanks for the link. And thank you for the work you do for this plugin.
