### ISSUE TITLE
[FEAT] IME Support: Avoid the tab key collision (Indenting list items vs Converting characters with IME)

### ISSUE THREAD

**Issue by yo-goto** [vslinko/obsidian-outliner#167]
**Describe the bug**
Continue from [my previous FEAT issue](https://github.com/vslinko/obsidian-outliner/issues/154).

>With Japanese IME, there are two kinds of key collision.
>
>1. Enter key collision(string converting vs breaking a line)
>2. Tab key collision(selecting predicated result in a popup window vs outliner indenting)
>
>Typing Japanese sentences requires to convert characters and then confirm the input with IME.
With Tab or Shift key to select predicated results in a popup window. With Enter key to determine the selection. 
>
>So, we have to push the Enter key twice to type a full sentence and break a line.
> (from https://github.com/vslinko/obsidian-outliner/issues/154)

Thanks to @vslinko, the feature to avoid the enter key collision was implemented.
But the tab key collision still exists. 

Please implement the feature to avoid the tab key collision.

**To Reproduce**
1. Try typing Japanese words or a sentence with Japanese IME
2. Popup window will show up
3. Use tab key to select a desirable predicated result.

**Expected behavior**
First tab key input should select a desirable predicated result like arrow keys.
Then, second tab key input should indent a list item.

**Screenshots**

![outliner feat tab key colliison](https://user-images.githubusercontent.com/50942816/124378407-1ce38f00-dcec-11eb-9a81-1abd3123fc4b.gif)

**Desktop (please complete the following information):**
OS: macOS BigSur 11.3
Obsidian Version: v0.12.9(insider build)

**Additional context**

**Comment by vslinko** [comment]
@yo-goto Thank you for your contribution! Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.2.8

**Comment by yo-goto** [comment]
Perfectly woking!
Thank you so much😻
