### ISSUE TITLE
[BUG] Exiting a list of tasks not possible by hitting Enter twice

### ISSUE THREAD

**Issue by janhink** [vslinko/obsidian-outliner#169]
**Describe the bug**
Without the Outliner plugin, I'm able to hit the Enter key twice to exit creating a list of tasks. This allows me to write some text, then create a list of tasks, and quickly continue writing text when I'm finished by hitting Enter twice. With the Outliner plugin, every time I hit enter, a new line with a task is created. It's hard to exit the task list and continue writing.

**To Reproduce**
1. Enter "- [ ] " to start a task list
2. Add some items (every Enter key creates subsequent "- [ ]")
3. Hit the Enter key twice to exit the task list
4. Instead of jumping from the task list, two "- [ ]" are created

**Expected behavior**
When hitting Enter twice in a task list, I expect to start a fresh line without the "- [ ]" being repeated

**Desktop (please complete the following information):**
 - OS: Windows
 - Obsidian Version: 0.12.9
 - Outliner plugin version: 1.3.0

**Comment by vslinko** [comment]
@janhink Thank you for your contribution! Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.3.1
