### ISSUE TITLE
[BUG] Creating a new item with Enter makes change in indent of the existing item 

### ISSUE THREAD

**Issue by iiz00** [vslinko/obsidian-outliner#17]
**Describe the bug**
When creating a new item with Enter key at the beginning of a line, indent of the existing item seems to be changed according to indent of the next line.

**To Reproduce**
1.
- item 1        ← hit Enter key at the beginning of the line 
    - item 2

2.
- (New item)
    - item 1
    - item 2
 indent of item 1 changes. 
(Then, reverse indenting item1 changes the order of items.)

**Expected behavior**
The state of indent of newly generated line by hitting Enter should be the same as the existing line.

**Desktop (please complete the following information):**
 - OS: windows 10 
 - Obsidian Version: 0.11.9

**Additional context**
Sorry for my poor English,
and thank you for your wonderful plugin!

**Comment by vslinko** [comment]
@iiz00 Thank you for your contribution!

Fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.0.7
