### ISSUE TITLE
[BUG] Not possible to append the current bullet point text (using Del button) with "Stick the cursor to the content" setting enabled

### ISSUE THREAD

**Issue by mikkovedru** [vslinko/obsidian-outliner#175]
**Describe the bug**
Not possible to append the current bullet point text (using Del button) with "Stick the cursor to the content" setting enabled.

**To Reproduce**
1. In settings make sure that `Stick the cursor to the content` is enabled (it is by default).
2. In a document, type the following:
```
- First
- Second

Third
```
3. Put the cursor at the end of the `- Second` line.
4. Press Del. The empty line before the `Third` is deleted.
5. Press Del. Press Del more. Frantically press Del many times. Nothing happens.

**Expected behavior**
After the second Del press, the word `Third` should have been appended to the `- Second` line, thus getting `- Second<CURSOR>Third`. Maybe that's what I want - to append the text in the already existing bullet point.

Or maybe I want to create a new bullet point. After pressing Enter, `Third` would become a new bullet point, thus getting:
```
- First
- Second
- Third
```

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.2 Cinnamon
 - Obsidian Version: 0.12.10

**Comment by vslinko** [comment]
@mikkovedru Thank you for your feedback! Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/2.0.3
