### ISSUE TITLE
[BUG] Tables/ Long LInes Are Truncated When Imrpove Style List Is Enabled

### ISSUE THREAD

**Issue by grassbl8d** [vslinko/obsidian-outliner#178]
**Describe the bug**

The tables are not appearing properly (being truncated)

**To Reproduce**

1. Enable Improve Style LIsts
2. Look at a long line/table.

**Expected behavior**
The table/line should not be truncated.

**Screenshots**

PLease see attached video.

![C2A5A4B1-E594-4C42-A3B5-CB2CD7F3BBFD](https://user-images.githubusercontent.com/93050/128313154-ca33bc5d-e224-4368-8b81-108b9baa4083.GIF)

**Comment by vslinko** [comment]
@grassbl8d thanks for the feedback. I can't reproduce the issue. It looks like it was fixed after the release of version 2.0. Could you try to install the latest version of the plugin and check the issue again?
