### ISSUE TITLE
Style inconsistency when text wraps and with multi-line entries

### ISSUE THREAD

**Issue by thenobody14** [vslinko/obsidian-outliner#179]
When text is long enough to wrap on to a new line, the wrapped lines are misaligned slightly to the left. In the *screenshot of current behaviour*, this can be seen at bullets 6 & 7 where the wrapped text beginning *"tempor.."* is shifted to the left. 

You'll notice that the text at line 9 (which is part of bullet 7, but after new-lines have been added) is aligned correctly, even when the text wraps onto the next line.

This behaviour also seems to cause a break in the vertical lines that indicate the indentation level. This can be seen in the *screenshot of current behaviour* where the expected vertical line between bullets 6 & 7 is missing; similarly the *"tempor..."* line at bullet 7 causes a gap in the vertical line, but the line reappears for lines 8 & 9. 

**Screenshot of current behaviour**
<img width="500" alt="Screenshot 2021-08-06 at 21 24 35" src="https://user-images.githubusercontent.com/54414085/128567963-b265b924-f2e2-415e-878c-221efb08c497.png">

I have created a mock-up of what I believe the expected behaviour should be. Hopefully you can see the changes that I have made, but I can explain if necessary.

**Mock-up of expected behaviour**
<img width="500" alt="Screenshot 2021-08-06 at 21 24 35-edit" src="https://user-images.githubusercontent.com/54414085/128570163-fe94b118-7ea5-4174-bee8-333969251439.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Obsidian Version: 0.12.12
 - Outliner Version: 1.3.1

Just wanted to add that I love the plugin. Keep up the good work.

**Comment by vslinko** [comment]
@thenobody14  Thank you for your feedback! Should be fixed after 2.0 release. Could you please check that everything is ok?

**Comment by vslinko** [comment]
Closed due to inactivity. If you are still experiencing the problem, please create a new issue.

**Comment by thenobody14** [comment]
Apologies for not responding sooner. Life got in the way. Have opened issue #251 as a continuation.
