### ISSUE TITLE
[FEAT] Title can't shown in  the outline bar

### ISSUE THREAD

**Issue by lvzhp** [vslinko/obsidian-outliner#18]
Thanks for you plugin,very useful.
But i've found  that if  i let some text turn First level title(h1) or(h2,3,4)
it can't be shown in the  outline bar.

**Comment by vslinko** [comment]
Hi @lvzhp !

Sorry, but I can't understand what are you suggesting. Could you please provide some extra details?

<img width="1281" alt="Screenshot 2021-03-28 at 11 04 44" src="https://user-images.githubusercontent.com/205823/112746091-6a49b500-8fb5-11eb-8053-6090c6236e19.png">

**Comment by danieltomasz** [comment]
I think I understood.
The behaviour described by the user is  that

```
 - # title
	 - ## Subtitle 
```
 is not interpreted as headers and the `# title` and `## Subtitle`  doesn't appear in the Outline tab. 

This is the default behaviour of the Obsidian (in Markdown syntax Headers starts line from` #` not `-` as in outline) and is not related  to the plugin. The issue might be closed I think.

**Comment by vslinko** [comment]
@lvzhp Please close the issue if you agreed with @danieltomasz

**Comment by vslinko** [comment]
I'm closing this issue. Please reopen if you disagree.
