### ISSUE TITLE
[BUG] Pressing *tab* while editing file name doesn't jump to note content

### ISSUE THREAD

**Issue by rubslopes** [vslinko/obsidian-outliner#180]
With the plugin enabled and with the cursor in the filename box (at the top of the note), pressing tab either does nothing or it changes the note content. It should move the cursor to the note content.

**To Reproduce**
1. Create a note with at least two bullet points.
2. Edit the content of the second bullet point.
3. Click in the note title box
4. Press tab
5. The second bullet point in the note content moves.

**Expected behavior**
Pressing tab while editing the note filename should move the cursor to the note content.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.6
 - Obsidian Version: 0.12.12

**Comment by vslinko** [comment]
@rubslopes Thank you for your feedback. Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/2.0.2
