### ISSUE TITLE
Dragging nodes with the mouse

### ISSUE THREAD

**Issue by MILKMILKKING** [vslinko/obsidian-outliner#184]
Dragging nodes with the mouse, currently it seems that you can only move nodes up and down by shortcut keys, it would be much easier if you could use the mouse to drag nodes in preview mode!

**Comment by dcoales** [comment]
I would also love this but would mostly want to be able to drag them in edit mode (I pretty much live in edit mode).  

In an ideal world I could just drag a single bullet OR highlight a set of lines and then drag all selected lines (similar to how I can highlight bunch of lines and then use a single command to delete them - the highlight doesn't have to cover the whole line).

CodeMirror does appear to support drag and drop so hopefully something like this would be possible :-)
