### ISSUE TITLE
[BUG] Opening another note when zoomed in maintains the outline bar

### ISSUE THREAD

**Issue by ShreyasKallingal** [vslinko/obsidian-outliner#19]
**Describe the bug**
After zooming in on a bullet, opening another note keeps the header bar at the top still.

**To Reproduce**
1. Zoom in on list
2. Open another note
3. Observe bar

**Expected behavior**
The outliner bar should only be shown for the original note.

**Screenshots**
Original note zoomed in:
![Screen Shot 2021-03-27 at 9 27 17 PM](https://user-images.githubusercontent.com/23715862/112742412-36ce4280-8f43-11eb-8755-7b42a9c39137.png)

New note:
![Screen Shot 2021-03-27 at 9 28 01 PM](https://user-images.githubusercontent.com/23715862/112742432-4fd6f380-8f43-11eb-8ca0-e4921918440a.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Obsidian 11.10

**Comment by vslinko** [comment]
@ShreyasKallingal Thank you for your contribution! Fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.0.8
