### ISSUE TITLE
[BUG] :  The TAB button is not working in kanban board when outliner plugin is enabled . When disabled it is working .please fix it 

### ISSUE THREAD

**Issue by skillhacker-code** [vslinko/obsidian-outliner#198]
**Describe the bug**
[BUG] :  The TAB button is not working in kanban board when outliner plugin is enabled . When disabled it is working .please fix it 
**To Reproduce**
1. Enable outliner
2. enable kanban plugin 
3. create card
4. try to type text and intent something under it 
5. tab will not work
6. disable outliner 
7. tab button will work

**Expected behavior**

**Screenshots**

![x05ES3A0zo](https://user-images.githubusercontent.com/68536959/133534574-82fb6de0-3c0c-4a07-b818-dae8e8b53b2c.gif)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Obsidian Version: 0.12.5

**Additional context**

**Comment by vslinko** [comment]
@skillhacker-code Thank you for your feedback. Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/2.0.2
