### ISSUE TITLE
Outliner CSS misaligned for many custom themes

### ISSUE THREAD

**Issue by danieltomasz** [vslinko/obsidian-outliner#2]
Outline CSS works for default Obsidian theme. But for many themes is misaligned
![image](https://user-images.githubusercontent.com/7980381/112561822-3c5a4a00-8dd6-11eb-8c54-654b6be26d79.png)
Here is example `obsidanian_ia` theme.

Probably there is no easy hack that will make it work?
If there is no hack, maybe information that "Better lists styles" works with default Obsidian theme and might not work well for other themes may be suffucient/

**Comment by vslinko** [comment]
Yes, I think it's impossible to make the snippet work well with all possible themes.
I'll add note that snippet tested only with default theme.

**Comment by vslinko** [comment]
Added disclaimer in README file. https://github.com/vslinko/obsidian-outliner#better-lists-styles
