### ISSUE TITLE
[FEAT] Delete extra bullet point and spaces at one time

### ISSUE THREAD

**Issue by iiz00** [vslinko/obsidian-outliner#20]
**Is your feature request related to a problem? Please describe.**
When I deleted the whole content of a line and the content of the next line came up to the current line, I have to press Del key a few times to delete bullet point and spaces.

**Describe the solution you'd like**
I don't know if it's possible, but it might be useful if pressing Del key at the end of a line immediately deletes extra bullet point and spaces which come from the next line.

**Describe alternatives you've considered**
Press Del key as many times as needed

**Comment by vslinko** [comment]
Hi @iiz00 !

Sorry, but I can't understand what are you suggesting. Could you please provide some extra details? Screen recording would be helpful.

**Comment by iiz00** [comment]
![ss](https://user-images.githubusercontent.com/58110075/112749499-9426ca00-8ffd-11eb-9b46-4b8b7920329a.jpg)
Sorry, I'm not good at English.
When pressing Del key at the end of line 2 and 5, I have to push Del key two more times to delete "-" and a space to get a dynalist-like result.
And now, I noticed that Shift + Del is a workaround for this.

**Comment by vslinko** [comment]
Ow, I got it. You meat `Del`, not `Backspace`.
Ok, I'll see what I can do.

**Comment by vslinko** [comment]
@iiz00 Thank you for your contribution! Should work in https://github.com/vslinko/obsidian-outliner/releases/tag/1.0.17
