### ISSUE TITLE
[BUG] Move sublists up | down only sometimes works

### ISSUE THREAD

**Issue by cweekly** [vslinko/obsidian-outliner#200]
I love Outliner, as it's helping me wean off Roam.

But the "move sublists up | down" default hotkeys -- Cmd + Shift + (up or down arrow) -- will often select + highlight text instead of moving the item as intended. It's so frustrating. I can't determine what circumstances are different when it works vs when it doesn't. I'll post more details here if/when I can reproduce it working or failing in a specific context.

Thanks very much to anyone who can shed light here!

**Desktop**
 - OS: MacOS 10.13.6
 - Obsidian Version: 0.12.15

**Comment by cweekly** [comment]
UPDATE: 
Still no luck determining why it only sometimes works... but FTR:  
* If you first select text with Shift+up|down arrow, and then press Cmd, it reproduces the problem behavior -- which randomly occurs even when there is no text selected.   
* For now I'm side-stepping the issue altogether and avoiding potential by changing the hotkeys config to use Cmd+Ctl+(up|down arrows) instead of the default Cmd+Shift+(up|down arrows).

**Comment by cweekly** [comment]
Closing, bc this problem disappeared sometime in the last ~month. :)

FTR, I'm now on 
MacOS 11.6 Big Sur
Obsidian v0.13.2 (insiders)
Outliner v1.4.0

**Comment by bySandboxer** [comment]
I have the same problem even after the updates. Sometimes it works, sometimes it does not and it seems to be document or even list-specific.

macOS 12.0.1 Monterey
Obsidian v0.13.14
Outliner v1.4.0
