### ISSUE TITLE
[BUG] Unable to Tab when a document is docked on the right or left side bar. 

### ISSUE THREAD

**Issue by Nitaicandra** [vslinko/obsidian-outliner#201]
**Describe the bug**
Unable to Tab when a document is docked on the right or left side bar. 
this does not happen when i disable the add-on

video:
https://user-images.githubusercontent.com/89361982/135701163-e094e2b1-8d83-42c7-836a-379675f73061.mp4

**Desktop (please complete the following information):**
 - OS: [Windows
 - Obsidian Version: [0.12.15]

**Comment by vslinko** [comment]
@Nitaicandra Thank you for your feedback! Should be fixed after 2.0 release. Could you please check that everything is ok?

**Comment by lmosakowski** [comment]
I just confirmed that this now works as expected in the 2.0 release.
