### ISSUE TITLE
[BUG]Open a File by Link, Can not locate

### ISSUE THREAD

**Issue by wslldsdhii** [vslinko/obsidian-outliner#206]
**Describe the bug**
If article A references article B, I can locate the location of A where references B through article B.
Bug: If active this plugin, 
This operation, locating the last location, conflicts with Obsidian's operation, which opens the file and locates it.

**To Reproduce**
1. Create a file "test01" and a file "test02".
2. open "test01", refer "test02" like `[[test02]]`, put it at the top of "test01"
3. append some text to "test01", and scroll down 
4. open "test02", click Backlinks of "test01", you will find that can not locate.

**Comment by vslinko** [comment]
@wslldsdhii Thank you for your feedback, but I cannot reproduce the issue. Could you provide more details, such as a screen recording?

**Comment by vslinko** [comment]
![Screen Recording 2021-12-09 at 21 54 54 mov](https://user-images.githubusercontent.com/205823/145458557-c3dc491e-965e-480b-86f9-5d1a6002cbbb.gif)

**Comment by vslinko** [comment]
Closing the issue due to inactivity.
