### ISSUE TITLE
Using the same hotkey for Fold/unfold 

### ISSUE THREAD

**Issue by kepano** [vslinko/obsidian-outliner#207]
Suggestion — it would be useful if the folded/unfolded state could be toggled on and off with a single hotkey.

**Comment by vslinko** [comment]
@kepano thank you for your suggestion. you can already use it by configuring "Toggle fold on the current line" hotkey.

**Comment by sublimino** [comment]
> you can already use it by configuring "Toggle fold on the current line" hotkey.

This works for me, thanks. 

However as a new user I was recently confused until finding this issue, as the hotkey setting is not with the rest.

Should I raise a new issue for this?

![image](https://user-images.githubusercontent.com/134117/152642887-4a4b1bf3-ba90-4c0b-9d36-df52b27c64e5.png)

vs

![image](https://user-images.githubusercontent.com/134117/152642906-60c26b7b-5715-41a8-86ae-035d355a4414.png)

**Comment by vslinko** [comment]
Hi @sublimino,

What are your expectations? Do you want to have the similar folding toggle feature in the Outliner plugin?

**Comment by sublimino** [comment]
As a new user I wasn't aware of the toggle fold feature, so perhaps either a note in the obsidian-outliner readme that it exists, or a similar feature in the outliner plugin if there's an appropriate way to do it.

**Comment by vslinko** [comment]
@sublimino ok, I understand, thank you.

Could you please open a new [discussion](https://github.com/vslinko/obsidian-outliner/discussions/categories/ideas) about this idea to keep it visible.
