### ISSUE TITLE
[BUG] Relationship Lines are broken with some Themes

### ISSUE THREAD

**Issue by rodrigo-rufino** [vslinko/obsidian-outliner#208]
**Describe the bug**
Relationship lines are broken with some Themes (example: Minimal Theme).

**To Reproduce**
1. Enable the Outliner Plugin
2. Enable Minimal Theme

**Expected behavior**
![Screenshot from 2021-10-18 13-37-59](https://user-images.githubusercontent.com/18670446/137772747-f1307dad-08ba-474c-994c-bc33fcee2652.png)

**Screenshots**
![Screenshot from 2021-10-18 13-38-10](https://user-images.githubusercontent.com/18670446/137772760-96ecae1a-ce15-473e-b2a9-39231098de7d.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu, Windows.
 - Obsidian Version: v0.12.15
 - Minimal Theme version: 4.0.4
 - Outliner Version: 1.4.0

**Comment by vslinko** [comment]
@rodrigo-rufino  Thank you for your feedback.

As the [disclaimer](https://github.com/vslinko/obsidian-outliner#improve-the-style-of-your-lists) says, "Styles are only compatible with built-in Obsidian themes".

After https://github.com/vslinko/obsidian-outliner/releases/tag/2.0.5 all styles improvements will be automatically disabled if Obsidian theme is not default.
