### ISSUE TITLE
[BUG] Cannot Zoom in same Outline in two leaf

### ISSUE THREAD

**Issue by Quorafind** [vslinko/obsidian-outliner#21]
**Describe the bug**
When I wanted to zoom in or out the same outline in two different leaf, one of them cannot be edited.

**To Reproduce**
1. Created a new leaf of same document
2. Use hotkey to zoom in the same outline(and have zoomed in the same outline in another document.)
3. See error

**Expected behavior**
Can zoom in different item of the same outline in different leaf.

**Screenshots**
https://user-images.githubusercontent.com/13215013/112749875-c1707980-8ff7-11eb-90d1-62ee139733cc.mp4

**Desktop (please complete the following information):**
 - OS: macOS
 - Obsidian Version: 0.11.10

**Additional context**
NULL

**Comment by vslinko** [comment]
@Quorafind Thank you for your contribution! Released in https://github.com/vslinko/obsidian-outliner/releases/tag/1.0.11
