### ISSUE TITLE
[BUG] Vertical relationship lines misaligned

### ISSUE THREAD

**Issue by jjgerr** [vslinko/obsidian-outliner#213]
**Describe the bug**
Indenting beyond level 3 causes the vertical line to not be properly aligned

**To Reproduce**
1. Create outline list with 4 levels of indentation

**Expected behavior**
The vertical line should appear similar to Level 1 and 2 indentations

**Screenshots**
<img width="245" alt="ss_20211105_124020_Vault1 - Obsidian v0 12 19" src="https://user-images.githubusercontent.com/71235134/140569098-48c97810-fceb-4e00-8c29-4d2bce2e6615.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Obsidian Version: v0.12.19
 - Outliner Version: 1.4.0

**Comment by vslinko** [comment]
@jjgerr Thank you for your feedback.

As the [disclaimer](https://github.com/vslinko/obsidian-outliner#improve-the-style-of-your-lists) says, "Indentation lines works only with tab size 4".

After https://github.com/vslinko/obsidian-outliner/releases/tag/2.0.4 vertical lines will be automatically hidden if the tab size is not 4.
