### ISSUE TITLE
[BUG] Creating a new bullet on a folded bullet adds a child bullet rather than a sibling

### ISSUE THREAD

**Issue by jsmorabito** [vslinko/obsidian-outliner#215]
**Describe the bug**
When I click enter with my cursor at the end of the active line of a folded bullet I expect a new bullet to be created underneath the current, on the same level. Instead it creates a child bullet inside the folded area.

**Comment by vslinko** [comment]
@jsmorabito thank you for the feedback! should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/2.0.9
