### ISSUE TITLE
[BUG] Page Position Changes When Outdenting, Indenting, or Reordering Folded List Items

### ISSUE THREAD

**Issue by julroger2013** [vslinko/obsidian-outliner#217]
**Describe the bug**
When indenting, outdenting, or reordering folded list items on a list that is long enough to make the page scrollable even when folded, the page's scroll position will suddenly jump downward. 

**To Reproduce**
1. Create a bullet-point list involving multiple bullet points and subpoints. The list should be long enough that even when the entire list is folded the page is scrollable due to its length.
2. Fold all lists (again, the page must be long enough to be scrollable *after* all lists are folded)
3. Attempt to indent, outdent, or reorder list items (using Outliner functions, not Obsidian's native "swap line")
4. Page position should jump down towards the bottom of the page, rather than retaining a stable scroll position

**Expected behavior**
Page position should remain stable (rather than scrolling to elsewhere on the page) when reordering, indenting, or outdenting folded list items using the Outliner Plugin.

**Screenshots**
No screenshot, but a short video recording is attached. The video first shows using Outliner functions in the unfolded list, which works perfectly. I then fold the list and attempt to indent/outdent, at which point the page's scroll position suddenly changes.

**Desktop (please complete the following information):**
 - OS: Windows 10 & MacOS Monterey 
 - Obsidian Version: v0.13.5 (Insider Build, but bug occurred even after rolling back to earlier, non-Insider versions)

**Additional context**
The primary difficulty caused by this bug is that I prefer to fold sub-bullets while outlining so that I can reorder and reorganize the major points of the outline while keeping the more detailed sub-bullets hidden.

https://user-images.githubusercontent.com/94991208/143296429-9a9b00c0-51f4-4038-b592-d4a6b436cd08.mp4

**Comment by vslinko** [comment]
@julroger2013 Thank you for your feedback! Should be fixed after 2.0 release. Could you please check that everything is ok?

**Comment by julroger2013** [comment]
Yes, I’m using it presently and should soon have a long enough document to
check! Thanks for the update—its adds so much value to Obsidian!

**Comment by julroger2013** [comment]
So far as I can tell, the previous bug has been eliminated. The scrolling
position remains stable even when working with folded list items.

**Comment by vslinko** [comment]
Good! So, i’m closing the issue.
