### ISSUE TITLE
[FEAT] Debug mode

### ISSUE THREAD

**Issue by vslinko** [vslinko/obsidian-outliner#22]
**Is your feature request related to a problem? Please describe.**
People reports bugs that I can't reproduce.

**Describe the solution you'd like**
Debug mode that produces logs to investigate bugs.

**Describe alternatives you've considered**
Ask some questions.

**Additional context**
—

**Comment by danieltomasz** [comment]
Could Asking for Toggling Developer Tools and reporting output/Turning off other plugins might help?

**Comment by vslinko** [comment]
I'm closing the issue. I'll add logs on demand.
