### ISSUE TITLE
[BUG] Things and Yin Yang themes incompatibility

### ISSUE THREAD

**Issue by lukthony** [vslinko/obsidian-outliner#225]
Slight incompatibility with both the Things and Yin Yang themes.

On Things:
<img width="264" alt="Screen Shot 2021-12-10 at 2 01 41 AM" src="https://user-images.githubusercontent.com/65358837/145538652-a1a67d95-f0c1-4c70-9493-068ec1301152.png">

On Yin Yang:
<img width="406" alt="Screen Shot 2021-12-10 at 2 03 03 AM" src="https://user-images.githubusercontent.com/65358837/145538832-e0a72ede-a401-4fce-ba3a-170ddce04f6c.png">

**Comment by vslinko** [comment]
@lukthony   Thank you for your feedback.

As the [disclaimer](https://github.com/vslinko/obsidian-outliner#improve-the-style-of-your-lists) says, "Styles are only compatible with built-in Obsidian themes".

After https://github.com/vslinko/obsidian-outliner/releases/tag/2.0.5 all styles improvements will be automatically disabled if Obsidian theme is not default.
