### ISSUE TITLE
[BUG] Outline bullet has not formed correctly it appears 2 bullet next to each other

### ISSUE THREAD

**Issue by Dennyyusuf** [vslinko/obsidian-outliner#226]
**Describe the bug**
- Outline bullet has not formed correctly it appears 2 bullet next to each other.
- The line level also unable to appear

**Expected behavior**
The bullet should appear only 1 bullet with line indicating the level

**Screenshots**
<img width="482" alt="image" src="https://user-images.githubusercontent.com/65077044/145560958-a720ba94-3d34-469e-aae4-4f4b8ee993d4.png">

**Desktop (please complete the following information):**
 - OS: MacOs Monterey 12.1 Beta 
 - Obsidian Version: 0.13.8 (insider)

**Comment by dariuszkowalski-com** [comment]
I see this in Live Preview mode
 Windows 10,  Obsidian 13.10 / Minimal Theme

**Comment by vslinko** [comment]
@Dennyyusuf Thank you for your feedback! Should be fixed after 2.0 release. Could you please check that everything is ok?

**Comment by vslinko** [comment]
Closed due to inactivity. If you are still experiencing the problem, please create a new issue.
