### ISSUE TITLE
[BUG]inconsistent indentation theming inside code blocks 

### ISSUE THREAD

**Issue by eccentrichead** [vslinko/obsidian-outliner#227]
**Describe the bug:**
In the latest obsidianMD release the outliner plugin seems to behave inconsistently especially with code blocks in nested bullet points. It seems to highlight the indents/spaces inside the code blocks leading to a strange-looking format. 
![image-1](https://user-images.githubusercontent.com/23582238/145575605-d4099664-f45b-4d61-99f7-91fd0eaf02ea.png)

If the nested bullet with the code blocks is folded, the indent still gets highlighted which affects the appearance. This occurrence has been tested in the default obsidian theme.
![image-2](https://user-images.githubusercontent.com/23582238/145575716-48a5a382-1094-4d69-a42e-8cfa0e470636.png)

This does not affect anything in the preview mode. It is quite distracting. There are some instances where under the above condition if there is a manual indentation error, the indent highlight created by the plugin ends up stretching to the full extent of the whole note (sample image of issue not available at the time of writing). 

**To Reproduce:**
1. Install obsidian
2. Install the outliner plugin
3. Create a note with nested bullets having code blocks.
4. Review the output in edit mode for the note.

**Expected behavior:**
The indentation marker should ideally not follow or get into the code blocks that is nested in such above way. 

**Desktop (please complete the following information):**
 - OS: Linuxmint 20.2
 - Obsidian Version: 0.12.19

**Additional context:**
none

**Comment by vslinko** [comment]
@eccentrichead thank you for the feedback! should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/2.0.10
