### ISSUE TITLE
[BUG] It's possible to select & edit invisible lines when zoomed in

### ISSUE THREAD

**Issue by jjsteffen3d** [vslinko/obsidian-outliner#23]
**Describe the bug**
When zoomed in, it's possible to place the cursor in invisible lines by using the arrow keys or mouse, and to edit the invisible lines.

**To Reproduce**
1. create list
2. zoom in on item that has something above or below
3. press arrow keys or click above/below current item to select invisible line
4. type something

**Expected behavior**
It is not possible to select and/or edit invisible lines.

**Screenshots**
![obsidian_outliner_invisible_lines](https://user-images.githubusercontent.com/27488268/112764826-92afce80-900a-11eb-9841-8634bd216f03.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Obsidian Version: 0.11.9

**Additional context**
Thanks for implementing the feature so quickly!

**Comment by vslinko** [comment]
@jjsteffen3d Thank you for your contribution! Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.0.12
