### ISSUE TITLE
[BUG] - line selected for moving up|down is randomly deselected 

### ISSUE THREAD

**Issue by cweekly** [vslinko/obsidian-outliner#230]
**Describe the bug**
When moving a given line up or down (via CMD+SHIFT+up-arrow|down-arrow), the line being acted on will randomly change.
So taking the "active" line and moving it up by 3 or 4 lines by repeating the hotkey combo can lead to arbitrary shuffling instead of predictable edits.

**To Reproduce**
1. Put cursor focus on a list element or line of text which has several peers above it
2. Use the CMD+SHIFT+up-arrow hotkey to move the selected line up by one
3. Repeat step (2) a few times
4. Note that instead of continuing to move the selected line, instead a different line is selected and operated on. 

**Expected behavior**
Consistent handling of the cursor focus and element being controlled

**Desktop (please complete the following information):**
 - OS: MacOS 11.6.2
 - Obsidian Version: v0.13.12
 - Plugin Version: v1.4.1

**Comment by vslinko** [comment]
@cweekly  thank you for your feedback.

Unfortunately Outliner plugin currently does not support a new editor, which was added in Obsidian 0.13.

Could you check if the issue reproduces when "Use legacy editor" is enabled?

**Comment by vslinko** [comment]
Closed due to inactivity. If you are still experiencing the problem, please create a new issue.
