### ISSUE TITLE
Command failed to execute

### ISSUE THREAD

**Issue by paulpetrutoni** [vslinko/obsidian-outliner#231]
I keep getting ; `Command failed to execute: obsidian-outliner:move-list-item[up|down]` - `TypeError: editor.firstLine is not a fucntion` and so on, in the Console. 
I tried enabling and disabling the core functionality having to do with list and heading folding but the plugin does not seem to work. 
Tried searching for info on Discord and forum but since I didn't find anything and can't think of things to try, I wanted to report this behavior. T

**Comment by vslinko** [comment]
@paulpetrutoni  thank you for your feedback.

Unfortunately Outliner plugin currently does not support a new editor, which was added in Obsidian 0.13. Please consider turning on the "Use legacy editor" setting until full support of the new editor is released.

Please follow #216 to be notified when the modern editor is supported.

**Comment by paulpetrutoni** [comment]
@vslinko Thanks for the personal reply on such a generic and personal issue! I understand and can imagine it's totally different, and assumed something of the sort but could not find any forum/discord talk regarding outliner & new editor. Thanks again.
