### ISSUE TITLE
Doesn't work at all in Obsidian for Linux

### ISSUE THREAD

**Issue by PhilLovesToCode** [vslinko/obsidian-outliner#232]
I'm running Obsidian for Linux. The outliner plugin doesn't work at all.  I'm sure it is enabled. I've tried all the hotkeys and none of them work. I also tried disabling all other plugins to avoid conflicts. The outliner commands appear in the command palette, but none of them do anything when selected.

**Comment by teranex** [comment]
I can confirm this. Have exactly the same behavior on Xubuntu

**Comment by vslinko** [comment]
@PhilLovesToCode thank you for your feedback.

Unfortunately Outliner plugin currently does not support a new editor, which was added in Obsidian 0.13. Please consider turning on the "Use legacy editor" setting until full support of the new editor is released.

Please follow #216 to be notified when the modern editor is supported.
