### ISSUE TITLE
[BUG] Move and indent list and sublists doesn't work any longer

### ISSUE THREAD

**Issue by Archie-2021** [vslinko/obsidian-outliner#233]
it was working fine before but after that last obsidian update these no longer working(hitting the key causes nothing):

 - move list and sublists up
 - mover list and sublists down
 - indent list and sublists
 - outdent list and sublists

**Comment by vslinko** [comment]
@Archie-2021 thank you for your feedback.

Unfortunately Outliner plugin currently does not support a new editor, which was added in Obsidian 0.13. Please consider turning on the "Use legacy editor" setting until full support of the new editor is released.

Please follow https://github.com/vslinko/obsidian-outliner/issues/216 to be notified when the modern editor is supported.

**Comment by Archie-2021** [comment]
thanks, looking forward for it
