### ISSUE TITLE
[BUG] CM6 - Block got folded up randomly

### ISSUE THREAD

**Issue by b1uegh0st** [vslinko/obsidian-outliner#236]
**Describe the bug**
Thanks for the CM6 support upgrade. This is a bug of a block got folded when 

**To Reproduce**
1. Fold one of the child bullet-point (usually the 1st one I think).
2. Any `arrow down` or `mouse click` on that folded up line or on the parent line will fold the whole block. (illustrated with screenshot)

**Expected behavior**
This kinda interfere with my workflow of folding each child block once I finished writing to continue with the next child.

**Screenshots**

Normal state for moving arrow updown
![image](https://user-images.githubusercontent.com/6695697/147497941-b274baae-7fab-4a8d-bbf1-083f90e41463.png)

This is the problematic state, an arrow down will fold the whole thing
![image](https://user-images.githubusercontent.com/6695697/147498192-4a61c2d6-1788-4acb-b42c-cef9cc263625.png)

An arrow down and then
![image](https://user-images.githubusercontent.com/6695697/147498228-0e77f88b-3d97-41b3-8638-33c70ad85889.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Obsidian Version: 0.13.16
 - plugin version: 2.0.0

**Additional context**
Not entirely sure if this is the plugin's problem or Obsidian's. If it's not yours can you note so that I can redirect to the forum.

**Comment by vslinko** [comment]
@b1uegh0st Thank you for your feedback. Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/2.0.1

**Comment by b1uegh0st** [comment]
Thanks for the prompt response and action. It is a confirmed fix
