### ISSUE TITLE
[FEAT] Auto outdent instead of exiting list

### ISSUE THREAD

**Issue by Dreamsync** [vslinko/obsidian-outliner#24]
**Is your feature request related to a problem? Please describe.**
Currently, if you are deep in a nested list and you hit enter, a new blank sibling bullet is created. If you hit enter again, you exit the list entirely. 

**Describe the solution you'd like**
The behavior should mirror how outliner apps work - hitting enter on a blank bullet should auto-outdent rather than exit the list. Consecutive enter presses would continue to outdent until reaching the root of the tree, at which point another enter press would exit the list.

**Comment by vslinko** [comment]
@Dreamsync Thank you for your contribution! Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.0.13
