### ISSUE TITLE
[BUG] Normal indentation causes a list and sublists indentation (outdentation)

### ISSUE THREAD

**Issue by Archie-2021** [vslinko/obsidian-outliner#243]
**Describe the bug**
when I hit TAB button it moves the list and sublists instead of just the item at current link. it was not the case couple of days ago.

so hitting TAB on "b" causes it to go  from:
- a
- b
    - c

to:

- a
    - b
        - c

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Obsidian Version: [e.g. 22]

**Additional context**

**Comment by vslinko** [comment]
@Archie-2021 Thank you for your feedback.

This is an expected behavior and a basic feature of the Outliner plugin.
You can disable this behavior by turning off the "Enhance the Tab key" option in the plugin settings.

**Comment by Archie-2021** [comment]
> @Archie-2021 Thank you for your feedback.
> 
> This is an expected behavior and a basic feature of the Outliner plugin. You can disable this behavior by turning off the "Enhance the Tab key" option in the plugin settings.

thanks, it works now. Is this the only effect of turning off `Enhanced Tab` option? I don't have a lot of experience with other outliners

**Comment by vslinko** [comment]
@Archie-2021 Yes, this is the only effect of `Enhanced Tab`
