### ISSUE TITLE
issue using the plugin

### ISSUE THREAD

**Issue by biniv** [vslinko/obsidian-outliner#247]
The plugin surprisingly works on the existing documents, but not on the new ones I create. Please help.

**Comment by vslinko** [comment]
@biniv this is weird. please provide more information: a screen recording and an example of the broken file.

**Comment by biniv** [comment]
https://www.loom.com/share/33949b73107a43c195cace557ad09861

Please let me know if I'm doing anything incorrectly. Thanks!

**Comment by vslinko** [comment]
@biniv You need to press <kbd>-</kbd> button to create a list.

Instead of:

```
test
test
  test
```

Please write:

```
- test
- test
  - test
```

**Comment by biniv** [comment]
Duh!! 
Thanks for your patience, and the amazing plugin!
Cheers
