### ISSUE TITLE
[BUG] Cannot delete list line if there's non-list line above

### ISSUE THREAD

**Issue by jjsteffen3d** [vslinko/obsidian-outliner#25]
**Describe the bug**
When the line above the list is not part of the list, it's not possible to completely delete the list with backspace. (workaround is ctrl+A and then backspace)

**To Reproduce**
1. create a line with anything except a list(can be empty or text)
2. create list below
3. try to completely delete list with backspace

**Expected behavior**
It's possible to completely remove the list with backspace.

**Screenshots**
![obsidian_outliner_delete_line](https://user-images.githubusercontent.com/27488268/112769089-85e9a580-901f-11eb-99e7-71dff0b40412.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Obsidian Version: 0.11.9

**Additional context**
Thank you for making this awesome plugin!

**Comment by vslinko** [comment]
@jjsteffen3d Thank you for your contribution! Fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.0.14
