### ISSUE TITLE
Style inconsistency when text wraps and with multi-line entries

### ISSUE THREAD

**Issue by aaronsmith1203** [vslinko/obsidian-outliner#251]
This is a continuation of the issue reported in issue #179 

> This behaviour also seems to cause a break in the vertical lines that indicate the indentation level. This can be seen in the screenshot of current behaviour where the expected vertical line between bullets 6 & 7 is missing; similarly the "tempor..." line at bullet 7 causes a gap in the vertical line, but the line reappears for lines 8 & 9.
> 
> <img width="660" alt="Screenshot 2022-01-16 at 15 35 52" src="https://user-images.githubusercontent.com/54414085/149666771-836536e9-d3cc-4b8c-804d-19d42ad8d887.png">

I can confirm that the issue still persists. Screenshot below shows the issue occuring in the 'Live Preview' editing mode, but the same behaviour occurs in the 'Source Mode' editing mode.

<img width="660" alt="Screenshot 2022-01-16 at 15 35 52" src="https://user-images.githubusercontent.com/54414085/149666999-b35bb514-7ba4-4d7f-be55-a17eb2885d25.png">

For this test, I started a new obsidian vault, and installed the Outliner plugin. I'm using the default light theme.

**Desktop (please complete the following information):**

OS: MacOS
Obsidian Version: 0.13.19
Outliner Version: 2.0.6

**Comment by vslinko** [comment]
@aaronsmith1203 thank you for you feedback!

I rewrote the entire vertical lines functionality in https://github.com/vslinko/obsidian-outliner/releases/tag/2.1.0.
Could you check if your problem is fixed?

**Comment by aaronsmith1203** [comment]
Hi @vslinko. Below is a screenshot of what I'm seeing on my existing Obsidian vault. The partial vertical lines are certainly gone, but I think my expectation is that there would be a vertical line between 'bullet 1' and 'bullet 2', and 'bullet 2' and 'bullet 3'.

![image](https://user-images.githubusercontent.com/54414085/152209695-e26d3352-3392-4d8b-980b-44995099eb59.png)

I have also just opened #270, regarding some strange behaviour I'm seeing when testing on a clean Obsidian vault. Probably worth us checking that this isn't an oddity on my end first?

**Comment by vslinko** [comment]
@aaronsmith1203 sorry, it seems I misunderstood, and this is a separate feature request, because I've copied Roam Research and Logseq's behavior - vertical lines are only drawn when there are child items.

Could you please create a new discussion about vertical lines for multiline entries https://github.com/vslinko/obsidian-outliner/discussions/categories/ideas

**Comment by aaronsmith1203** [comment]
Hey @vslinko. Yes, i see what you mean about the behaviour of Roam and Logseq. In which case. I agree that the bug of the broken vertical lines is resolved. I'll close this ticket.

I have been coming across a few behavioural quirks today, but I'll need time to verify the behaviour and what causes them. I'll post issues if they don't already exist, or haven't been patched in the mean time.

Many thanks for the plug-in and your continued support.
