### ISSUE TITLE
[BUG] Unable to create line after last one

### ISSUE THREAD

**Issue by ivan-lednev** [vslinko/obsidian-outliner#252]
**To Reproduce**
1. Zoom in on a list item that is not the last one in the larger block, but *is* the last one in its sublist
2. Hit "Enter"

**Expected behavior**
- A new list item is created
- The caret gets moved to the new item

**Actual**
- A new list item is created, but the hiding class gets attached to the HTML element
- The list item after the new one becomes visible instead
- The cursor stays on the first item

**Gif**
![last-item-zoom-bug](https://user-images.githubusercontent.com/41428836/128681911-788de917-55e7-4e2b-9a68-eec75f2d8aa4.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Obsidian Version: 0.12.13
 - Plugin Version: 1.2

**Comment by vslinko** [comment]
Should be fixed in https://github.com/vslinko/obsidian-zoom/releases/tag/0.2.7 and https://github.com/vslinko/obsidian-outliner/releases/tag/2.0.7
