### ISSUE TITLE
[BUG] Deleting the last item in a sub-list when zoomed in, unhides the next item in the parent list.

### ISSUE THREAD

**Issue by jackcaunter** [vslinko/obsidian-outliner#256]
**Describe the bug**
With "Stick the cursor to the content" enabled in Outliner, and the Zoom plugin installed:
When zoomed into a list with sub-items that also has other sibling lists under it, deleting the last visible item brings the next list into view. 
Disabling "Stick the cursor to the content" fixes the issue. (but then, that useful functionality is also disabled.)

**To Reproduce**
1. Make a list with some sub-items
![Obsidian_4uFVkFBkma](https://user-images.githubusercontent.com/51241502/130887146-00b1cc7b-c4c5-4fd7-a32d-295da4a1c594.png)

2. Zoom in on the first list
![Obsidian_8H6OuJQuiw](https://user-images.githubusercontent.com/51241502/130887161-ef0ca2fe-725f-48fa-877d-00dd6d21c11c.png)

3. Place cursor at the last empty item (with “Stick the cursor to the content” enabled in Outliner) …
![Obsidian_G3QsSEi9Sr](https://user-images.githubusercontent.com/51241502/130887175-b6b142d4-5db0-4f13-9704-57cfd81c2dcb.png)

4. Press backspace to delete the sub-item.
![Obsidian_DD0Wk0vmGz](https://user-images.githubusercontent.com/51241502/130887181-dd3f659a-0672-46af-87e6-0347ba687738.png)

The next item, which isn’t part of the list you’re currently working on, pops into view, causing you to have to go back to the first item and hit the zoom hotkey again.

**Expected behavior**
The last item is just deleted.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version: v0.12.12

**Comment by vslinko** [comment]
@jackcaunter thank you for your feedback! should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/2.0.8 and https://github.com/vslinko/obsidian-zoom/releases/tag/0.2.7
