### ISSUE TITLE
Add option to create horizontal space between indents

### ISSUE THREAD

**Issue by pcuellar** [vslinko/obsidian-outliner#257]
Currently, horizontal space between indents is rather small. I changed this via css but as a result paragraphs can become misaligned. It would be great to have an option that allows to increase horizontal space. Here are pictures before and after using snippets and the misalignment result

Without snippet. Correct alignment but indents very close to each other
![Screen Shot 2022-01-25 at 10 59 08 AM](https://user-images.githubusercontent.com/20482146/151013797-4775dce6-7085-4e8b-9882-d283b3e93974.png)

With snippet. More space between indents but text loses alignment
![Screen Shot 2022-01-25 at 10 58 41 AM](https://user-images.githubusercontent.com/20482146/151013958-d63b1869-0a57-41e2-a4af-ed10079e090b.png)

Here is the snippet I used
`.markdown-source-view.mod-cm6 .cm-hmd-list-indent .ig-tab {
    padding-right: 14px;
}`

**Comment by vslinko** [comment]
@pcuellar thank you for your feedback!

You can increase the horizontal space by increasing the "Tab size" setting.
I think that should solve your problem.
<img width="812" alt="Screenshot 2022-01-27 at 11 40 29" src="https://user-images.githubusercontent.com/205823/151323101-fc535934-1417-4ba5-b27d-8441bc2d77bf.png">
