### ISSUE TITLE
[BUG] Vertical lines are in the wrong place when "Draw vertical indention lines" is enabled and Obsidian window is not too narrow

### ISSUE THREAD

**Issue by RichSteele** [vslinko/obsidian-outliner#268]
**Describe the bug**
When the option "Draw vertical indentation lines" is enabled and the Obsidian window is not too narrow, the lines show up about 20% too far to the right.

**To Reproduce**
1. Go to Outline plugin options
2. Click on "Draw vertical indentation lines" option to enable
3. Open a page with nested bullets
4. See issue: there are extra lines to the right of the "regular ones." It's easiest to make them happen by maximizing the Obsidian window, but they will slowly separate from the regular lines as the window width increases.

**Expected behavior**
The lines of the right should not be there

**Screenshots**
Page when Obsidian is maximized:
![image](https://user-images.githubusercontent.com/2944434/152070118-3703dbed-391c-435c-87ef-f30e5a28b0a9.png)

This is the same page but with the window not maximized:

![image](https://user-images.githubusercontent.com/2944434/152070248-95265669-316c-409b-8528-7fa89e7ebdc7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version: 0.13.23; no custom CSS, default theme; I have not yet disabled any of my other plugins

**Comment by vslinko** [comment]
@RichSteele thank you for your feedback! should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/2.2.1

**Comment by RichSteele** [comment]
Thank you, I've confirmed the fix resolves this issue.
