### ISSUE TITLE
Beta plugin on iPad

### ISSUE THREAD

**Issue by griffimu** [vslinko/obsidian-outliner#269]
Hi - thank you for all of your great work!  I've tried installing the beta plugin using BRAT on the most recent insider build.  The plugin loads successfully, but it does not function as expected.  List bullets are not created automatically and it also seems to broadly interfere with writing in general.  Has anyone got the beta plugin to run successfully on an iPad for testing?

Thanks!

**Comment by vslinko** [comment]
@griffimu thank you for the feedback!
Yes, there are many bugs in the beta version that will be fixed in https://github.com/vslinko/obsidian-outliner/pull/267

**Comment by griffimu** [comment]
FYI - I have been periodically checking to see if the beta works with the new versions.  This morning I enabled Outliner mobile beta again and it seems to be working.  Obsidian now implements the vertical lines, so I disabled those, but the hotkeys to move around list items seem to be working.
