### ISSUE TITLE
Vertical lines are out of place on a clean vault

### ISSUE THREAD

**Issue by aaronsmith1203** [vslinko/obsidian-outliner#270]
**Describe the bug**
Using a new Obsidian vault with default settings and no other plugins, the **vertical lines** are shifted to the right when compared to the example on the [release 2.1.0](https://github.com/vslinko/obsidian-outliner/releases/tag/2.1.0) page.

Screenshot below.

![image](https://user-images.githubusercontent.com/54414085/152206706-b1cfd90b-abee-407c-baf8-2d3e2435ed15.png).

**To Reproduce**
1. Close Obsidian entirely
2. Go to 'Open another vault'
3. 'Create new vault'
4. Open 'Settings', allow plugins
5. Install _obsidian-outliner_ plugin
6. Test indenting, The result as shown in above screenshot.

**Desktop (please complete the following information):**
 - OS: MacOS 12.1
 - Obsidian version: 0.13.23
 - Outliner version: 2.2.1

**Comment by RoamanEmpire** [comment]
Same here

**Comment by WhiteNoiseDev** [comment]
they are because you haven't enabled fold lists.

I am wondering if (some of) the vertical line functionality can be moved to this other plugin
<https://github.com/mgmeyers/obsidian-indentation-guides>

**Comment by RoamanEmpire** [comment]
Where can we find this fold lists option?

**Comment by vslinko** [comment]
@aaronsmith1203 thank you for the feedback!

Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/2.2.2

**Comment by SeyeeL** [comment]
操作系统：MacOS 12.1
黑曜石版本：0.13.23
大纲版本：2.2.2 
win10上也是，竖线飘到了左边
![image](https://user-images.githubusercontent.com/71479570/153876662-34ad0f65-31a1-497a-ac01-49411ae3722a.png)

**Comment by Shaco-w** [comment]
在win11上也出现了相同的问题

**Comment by Shaco-w** [comment]
> 操作系统：MacOS 12.1 黑曜石版本：0.13.23 大纲版本：2.2.2 win10上也是，竖线飘到了左边 ![image](https://user-images.githubusercontent.com/71479570/153876662-34ad0f65-31a1-497a-ac01-49411ae3722a.png)

我也遇到了相同的问题，请问你是怎么解决的呀？

**Comment by SeyeeL** [comment]
@Shaco-w 我没用这个插件了哈哈哈

**Comment by vslinko** [comment]
@SeyeeL @Shaco-w 
Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/2.2.3
