### ISSUE TITLE
'Show line number' breaks alignment of vertical lines

### ISSUE THREAD

**Issue by aaronsmith1203** [vslinko/obsidian-outliner#271]
**Describe the bug**
When the 'show line number' option in Obsidian is enabled, the alignment of the vertical lines is broken.

![image](https://user-images.githubusercontent.com/54414085/152210859-b214d022-1690-498e-a251-9e713b979f1d.png)

**To Reproduce**
1. Go to the Obsidian settings
2. Enable 'show line number' in the 'Editor' options
3. View or create a new bullet list

**Desktop (please complete the following information):**
- OS: MacOS 12.1
- Obsidian version: 0.13.23
- Outliner version: 2.2.1

**Comment by vslinko** [comment]
@aaronsmith1203 thank you for the feedback!

Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/2.2.2

**Comment by aaronsmith1203** [comment]
@vslinko, I can confirm that this is working as expected. Thanks for the fix!
