### ISSUE TITLE
[BUG] Vertical-line drift with 'readable line length' option

### ISSUE THREAD

**Issue by aaronsmith1203** [vslinko/obsidian-outliner#273]
**Describe the bug**
When the Obsidian option 'readable line length' is enabled. If width of a note pane is wider than the pre-defined 'readable line length', the vertical-lines drift away from the text. They seem to follow the left of the note pane instead of the left of the editable area.

![image](https://user-images.githubusercontent.com/54414085/152700606-08cc0897-b925-44a3-9c64-5b80a8c36901.png)

**To Reproduce**
1. 'Create new vault', so no other plugins interfering
2. Ensure 'Readable line length' option enabled under 'Editor -> Display' options
3. Install _obsidian-outliner_ plugin
4. Open a single note, and create indented list
5. Resize the width of Obsidian app window to see how the vertical-lines stick to the left of the note pane.

**Desktop (please complete the following information):**
 - OS: MacOS 12.1
 - Obsidian version: 0.13.23
 - Outliner version: 2.2.2

**Comment by aaronsmith1203** [comment]
This is linked to issue #288

**Comment by vslinko** [comment]
Thank you all for the feedback!

Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/2.2.3

If the problem still persists, please create a new issue.
