### ISSUE TITLE
[BUG] Sometimes my indented bullets get erroneously converted to dashes

### ISSUE THREAD

**Issue by nbarman2022** [vslinko/obsidian-outliner#275]
**Describe the bug**
Sometimes my indented bullets get converted to dashes. Then the only way to get them to be bullets again is to basically remove all the indenting and hierarchy and re-create it from scratch... please help!

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Obsidian Version: [e.g. 22]

**Additional context**

**Comment by vslinko** [comment]
@nbarman2022 hi! unfortunately i can’t reproduce the issue. could you please provide more details like a screen recording or  steps to reproduce
