### ISSUE TITLE
Editor pane cut off / ridiculously tiny

### ISSUE THREAD

**Issue by MikeTannenbaum** [vslinko/obsidian-outliner#276]
**Describe the bug**
When the plugin is enabled, the editor window gets ridiculously small and unable to be used. 

**To Reproduce**
1. Enabled the Outliner plugin
2. Editor window gets tiny
3. Disable plugin
4. Editor works normally

**Expected behavior**
Editor to be fully visible

**Screenshots**
<img width="775" alt="CleanShot 2022-02-14 at 09 58 58@2x" src="https://user-images.githubusercontent.com/792648/153888204-db0a7826-b432-416d-92ef-75c620b9028e.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 12.2
 - Obsidian Version: 0.13.23

**Comment by vslinko** [comment]
@MikeTannenbaum thank you for the feedback!

do you have other plugins, themes or css snippets installed?

**Comment by MikeTannenbaum** [comment]
Hey @vslinko! I have other plugins installed, yes. However, I disabled all plugins and toggled them one by one. Upon toggling Outliner the display changes immediately, even when it's the only plugin enabled.

Hope that helps; I'm happy to answer any questions, but also don't want you to have to worry about my one use case error!

As it stands right now, it seems the plugin is working again for me. I have no idea what happened, as I haven't been on my computer since my first comment. So please consider this closed! I'll come back if it persists. Thanks for your work!

**Comment by jmhammond** [comment]
In case anyone else encounters this (I did):

To resolve it, uninstall the Outliner plugin and then reinstall it.  


My suspicion is that I had an older version installed;  I hadn't used obsidian in over a year having switched to logseq and now back again.
