### ISSUE TITLE
[BUG] Vertical lines displaced with Typewriter Scroll plugin

### ISSUE THREAD

**Issue by Elaws** [vslinko/obsidian-outliner#277]
When using Outliner with Typewriter Scroll plugin, vertical lines have a weird behavior :

![image](https://user-images.githubusercontent.com/52013479/153956319-fddcea4a-b6db-4581-8ac9-b42c06117834.png)

OS: Windows 10
Obsidian : v.0.13.23

**Comment by vslinko** [comment]
@Elaws Thank you for the feedback!

Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/2.2.4
