### ISSUE TITLE
[BUG] Cannot backspace to delete content when cursor is at end of a list item

### ISSUE THREAD

**Issue by ericaxu** [vslinko/obsidian-outliner#29]
**Describe the bug**
Cannot backspace to delete content when cursor is at end of a list item.

**To Reproduce**
1. Make a list item by typing "- Item"
2. When the cursor is here: "- Item|", press `Backspace`

**Expected behavior**
The last character should be deleted, but it's not.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Obsidian Version: [e.g. 22] 0.11.7

**Additional context**
When the cursor is at that position, most keys work like `Delete`, `Enter`, and `ArrowRight`.
Very lovely plugin otherwise!

**Comment by ohlinn** [comment]
It works with `alt+delete` in Windows.

**Comment by aaronweewee** [comment]
Back space does not work with this plugin indeed, this is a really awesome plugin, hope this will be fixed

**Comment by ericaxu** [comment]
> It works with `alt+delete` in Windows.

Oh nice, thanks for letting me know about this workaround!

**Comment by iiz00** [comment]
In my environment, Backspace doesn't work completely (doesn't delete any character) in a bullet list in the present version(1.0.14).

**Comment by davecan** [comment]
I just experienced this exact same problem. Disabling the plugin restored the correct behavior.

Platform: MacOS 10.15.7
Version: 0.11.7

**Comment by vslinko** [comment]
Thank you all! Should be fixed in 1.0.15
