### ISSUE TITLE
Changes 0.13.26+ and 0.14

### ISSUE THREAD

**Issue by WhiteNoiseDev** [vslinko/obsidian-outliner#290]
This is just a notice that substantial changes were introduced in the way enter and shift-enter operate in Obsidian in 0.13.26. You may need to tweak something to adapt.

**Comment by WhiteNoiseDev** [comment]
Obsidian 0.14 implements a version of vertical lines natively.

**Comment by vslinko** [comment]
@WhiteNoiseDev Thank you for the notice!

It looks like everything is fine with enter and shift-enter.

I added a tweak for the native vertical lines — I hide them if Outliner's vertical lines are enabled.
