### ISSUE TITLE
[BUG] This plugin does not support your device.

### ISSUE THREAD

**Issue by gnat** [vslinko/obsidian-outliner#295]
![Screenshot_20220308-154518202](https://user-images.githubusercontent.com/24665/157344984-ced000c0-8c37-4b6b-91d6-38d5111941b4.jpg)

**Describe the bug**
Cannot install on Android.

**Desktop (please complete the following information):**
 - OS: Android
 - Obsidian Version: 38

**Comment by vslinko** [comment]
@gnat thank you for the feedback!

duplicate of https://github.com/vslinko/obsidian-outliner/pull/267
