### ISSUE TITLE
[BUG] Vertical line of note disappear 

### ISSUE THREAD

**Issue by ylcdwyyx** [vslinko/obsidian-outliner#296]
**Describe the bug**
Vertical line of note disappear 

**To Reproduce**

**Expected behavior**

**Screenshots**
the vertical line of note shows in old version like this 
<img width="151" alt="image" src="https://user-images.githubusercontent.com/58276890/157362040-f0deca97-8831-46d0-a9cf-a0e5533c8de7.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Obsidian Version: v0.13.31

**Additional context**

**Comment by vslinko** [comment]
Thank you all for the feedback!

Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/2.2.3

If the problem still persists, please create a new issue.
