### ISSUE TITLE
[BUG]New vertical line trigger covers the fold triangle button

### ISSUE THREAD

**Issue by ylcdwyyx** [vslinko/obsidian-outliner#297]
**Describe the bug**
New vertical line trigger covers the fold triangle button

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Obsidian Version: v0.13.31

**Comment by vslinko** [comment]
Thank you all for the feedback!

Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/2.2.3

If the problem still persists, please create a new issue.
