### ISSUE TITLE
[FEAT] expose commands instead of hardcoding hotkeys

### ISSUE THREAD

**Issue by manogna4** [vslinko/obsidian-outliner#30]
**Is your feature request related to a problem? Please describe.**
This is a very useful plugin, but the hardcoded hotkeys are stopping me from using it since many of them are defaults for other functions (at least on windows). Also I use some of them elsewhere.

Some hotkeys are *extremely* counter intuitive to me (and I think other people too). For example, backspace usually deletes a character, but here it deletes an entire item.

An advantage with the approach I suggest is that users will be able to search for commands in the command palette. They won't need to read your description every time they want to execute something new.

**Describe the solution you'd like**
expose commands so that hotkeys may be set from the obsidian UI. I'd recommend not settings defaults because lists are only a subset of what's possible in markdown, and it's very likely you will override defaults for commands that others consider intuitive.

**Describe alternatives you've considered**
I can download and change your plugin to unset some hotkeys, but not everyone will be able to do that.

**Comment by vslinko** [comment]
@manogna4 Thank you for your contribution! I can feel your pain with hotkeys.

I already have an issue about that so I'm closing this issue as a duplicate.
Please follow #7 to stay in touch.

**Comment by manogna4** [comment]
> @manogna4 Thank you for your contribution! I can feel your pain with hotkeys.
> 
> I already have an issue about that so I'm closing this issue as a duplicate.
> Please follow #7 to stay in touch.

sorry about the duplicate. a search for 'hotkeys' and 'shortcuts' turned up nothing.
