### ISSUE TITLE
[BUG] Getting an error "Unable to parse list: expected some indent, got no indent"

### ISSUE THREAD

**Issue by pamela-drouin** [vslinko/obsidian-outliner#305]
**Describe the bug**
When in the middle of editing a note, the shortcut for moving list/sublist up or down stopped working. The keyboard/cursor reverts to the behavior when the Outliner plugin is not installed where the editor tries to highlight all the text that occurs before the cursor's position, or after the cursor's position. 

When I attempted to troubleshoot it with the Developer Console, I see the message: `parseList Unable to parse list: expected some indent, got no indent`

**To Reproduce**
1. Go to a note in editor or source mode
2. Open up the Developer Console
3. Use the default keyboard shortcut for moving a list/sublist up or down to try to move a list or sublist item
4. Observe the behavior (it reverts to pre-plugin text highlighting behavior) 
5. See error in the Developer Console 

**Expected behavior**
I expect the shortcut for moving list/sublist up down to work, as in moving items.

**Screenshots**
[screenshot](https://www.dropbox.com/s/y3vu0dv66a1s1dx/Screen%20Shot%202022-03-17%20at%201.00.25%20PM.png?dl=0)

**Desktop**
 - OS: OSX 12.2.1
 - Obsidian Version: 0.14.2

**Comment by indiewelt** [comment]
same issue here. Tried with standard theme and also other themes

**Comment by mrpurplecloud** [comment]
> 

Thanks for providing the error message. It inspired me that the issue may have to do with indentation. And then I was able to solve it by replacing every instance of consecutive 4 spaces with a single tab in the problematic markdown file with notepad+.

**Comment by ryanwwest** [comment]
Noticing the same behavior with the hotkeys not responding.

**Comment by zarybnicky** [comment]
I've also encountered the problem, but in exactly the opposite manner than the previous report - if I replace all TAB characters from my list with four spaces, the hotkeys start working again,

**Comment by thomas-neuburger** [comment]
Same here. None of the Outliner move actions work. And I get better TAB and RETURN behavior if I turn the plugin off. 

OBS: 0.14.15
Linux Mint 20.3

**Comment by vslinko** [comment]
Hi all! Thanks for the feedback.

This error message occurs when a list has indentation issues. The plugin tries to parse lists using Obsidian's indentation settings. Please try to reindent your lists and keep the indentation consistent in all lists.

If you think you don't have indentation errors and the plugin isn't working correctly, please provide the markdown files containing the errors.

**Comment by gioknx** [comment]
Hi @vslinko I'm having the same problem!

I believe my lists does not contain any indentation errors; Just tested on multiple lists and pages, even freshly created ones

How can I prove you with the markdown files?

**Comment by vslinko** [comment]
Hi @gioknx 
You could create a new bug and attach the file that doesn't work properly.
