### ISSUE TITLE
[BUG] Vertical lines show wrong

### ISSUE THREAD

**Issue by cool-RR** [vslinko/obsidian-outliner#306]
Image:  ![](https://i.imgur.com/Ovp14Ty.jpg)

Source:

```
* boo
    * bar
    * bar
    * baz
        * bim
        * bim
            * dfsdf
        * sdfsd
    * SDF
```

**Comment by vslinko** [comment]
@cool-RR What theme do you have? Do you have custom css snippets?

**Comment by vslinko** [comment]
I added some css tweaks in https://github.com/vslinko/obsidian-outliner/releases/tag/2.2.5
@cool-RR Could you please check if this helps.

**Comment by cool-RR** [comment]
Default theme. Your new version fixed the problem, thank you! 

For posterity, here's my custom CSS: 

```
hr {
  border: 2px solid #333;
}

.theme-dark {
  --text-normal: #aaa;
  --background-primary: #010101;
  --background-secondary: #111;
  --background-secondary-alt: #222;
}

.outliner-plugin-list-line {
    margin: auto;
    background: red;
}

```
