### ISSUE TITLE
[BUG] vertical line misplaced when there is backlink panel at the bottom

### ISSUE THREAD

**Issue by QitianHu46** [vslinko/obsidian-outliner#307]
**Describe the bug**
<img width="686" alt="image" src="https://user-images.githubusercontent.com/15711759/159211568-a072b2b0-e332-483d-ba94-59b5a0074b0e.png">

When there is a backlink panel at the bottom of the page, the vertical lines of Outlier will be misplaced as I scroll to the bottom, as if there is no backlink panel and the text also scrolls down.

**Comment by vslinko** [comment]
@QitianHu46 thank you for the feedback!

duplicate of https://github.com/vslinko/obsidian-outliner/issues/304
