### ISSUE TITLE
Vertical line click does not zoom

### ISSUE THREAD

**Issue by aagha** [vslinko/obsidian-outliner#308]
**Describe the bug**
Even though set, when clicking on a vertical line, won't zoom in.

**To Reproduce**
1. In Outliner settings, make sure "Vertical indention line click action" is set to "Zoom In":
2. Create a set of nested bullets
3. Click on a vertical line

**Expected behavior**
When clicking on a vertical line, see the screen updated to the parent of that nested line be the top-most node and see a breadcrumb of where in the bulleted list structure you now are

**Screenshots**
Clicking this vertical line does nothing:

![image](https://user-images.githubusercontent.com/5522103/159367053-99b1a3c0-b656-4a67-9bce-4b6644b6fb35.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version: 0.13.33

**Comment by vslinko** [comment]
@aagha Thank you for the feedback. Do you have [Obsidian Zoom](https://github.com/vslinko/obsidian-zoom) installed?

**Comment by aagha** [comment]
Ooh! That did it.

I must have missed that. Thank you.
