### ISSUE TITLE
[BUG] Relationship lines on CSS snippet overlap symbols and empty lines

### ISSUE THREAD

**Issue by argenos** [vslinko/obsidian-outliner#31]
**Describe the bug**
Relationship lines from CSS snippet overlap symbols and include empty lines between lists. I see no relationship lines in preview mode.

**To Reproduce**
1. Copy the snippet from this repository
2. Save as a snippet in Obsidian and enable it
3. See result in edit mode

**Expected behavior**
Relationship lines shouldn't overlap with text across empty lines

**Screenshots**
Edit mode:
![image](https://user-images.githubusercontent.com/5426039/112823175-3cce3b80-9089-11eb-9a62-9418242b4fe9.png)

Preview mode:
![image](https://user-images.githubusercontent.com/5426039/112823378-7dc65000-9089-11eb-9809-3727d6cb9488.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Obsidian Version: 0.11.10

**Additional context**
N/A

**Comment by danieltomasz** [comment]
I cannot reproduce this behaviour (I am another user). Could you provide exact snippet content to reproduce this behaviour?
I remember having this behaviour when my markdown was badly formated (I have a tab and additional space or something like that)

**Comment by argenos** [comment]
Yeah, there might be something to a weird mixture of tabs/spaces. But I don't think this should have an influence on empty lines, would it? Here you go:

```markdown
**Bullets**

- Level 1
- Level 1
	- Level 2
		- Level 3
			- Level 4
- Level 1

1. one
	1. two
	2. two
3. three
	1. three one
		1. three one one
			1. three one one one
	2. three two
4. four

  - [ ] hello world

**Todos**

- [ ] Level 1
- [ ] Level 1
  - [ ] Level 2
  - [ ] Level 2
  - [ ] Level 3
    - [ ] Level 4
    - [ ] Level 5
    - [ ] Level 4
    - [ ] Level 4
  - [ ] Level 3
    - [ ] Level 4
  - [ ] Level 2
- [ ] Level 1
- [ ] Level 1

- [ ] level 0
  - [ ] level 1
```

**Comment by danieltomasz** [comment]
how its look on my computer;  is there a chance that GitHub autopretify formatting here?
![image](https://user-images.githubusercontent.com/7980381/112825762-72285880-908c-11eb-878e-52363f1e94c3.png)

**Comment by argenos** [comment]
Here is a GIF showing the problem on the default theme:
![Peek 2021-03-29 12-49](https://user-images.githubusercontent.com/5426039/112826377-3477ff80-908d-11eb-8018-f8c58daa3d02.gif)

I don't use the prettifier plugin. And you can see a different bug here: I can't use backspace to delete characters when I'm on a list.

**Comment by danieltomasz** [comment]
the bugrelated  backspace has opened issue https://github.com/vslinko/obsidian-outliner/issues/29

**Comment by danieltomasz** [comment]
Now I can reproduce 

Making one bullet +  empty line + bullets again cause strange behaviour

```
- A

	aaa
		bbb	
		ddd	
```
![image](https://user-images.githubusercontent.com/7980381/112827029-14950b80-908e-11eb-8f1a-7bf02fc88549.png)

**Comment by danieltomasz** [comment]
It may be related to this bug too https://github.com/vslinko/obsidian-outliner/issues/28

**Comment by argenos** [comment]
hmm the text from the demo gets relationship lines immediately for me:

```markdown
- new list
- another item
	- new lbullet
	- ok this works

this doesn't have a bullet anymore, why is there a line?

- check this other bug I just found
- I write here but I won't be able to delete
```

**Comment by vslinko** [comment]
@argenos Thank you for your contribution!
I can reproduce. Looks like Obisdian should have been configured to use spaces instead of tabs to reproduce.

**Comment by vslinko** [comment]
Fixed snippet already in `main` branch.
Current behaviour depends on how hypermd detects lists, so I can't do better.

<img width="417" alt="Screenshot 2021-03-29 at 18 09 48" src="https://user-images.githubusercontent.com/205823/112857859-f6450500-90b9-11eb-8ad8-94392961733c.png">
