### ISSUE TITLE
[FEAT] Longer development cycle  with beta branch for testing new features or releases after testing period

### ISSUE THREAD

**Issue by danieltomasz** [vslinko/obsidian-outliner#32]
**Is your feature request related to a problem? Please describe.**

The speed of development and reacting to the feature requests here is astonishing.
Adding new functionalities may introduce bugs to core functionalities. If the number of people who are using the plugin will increase it may cause more disruption for their workflow. Also, the number of urgent issues to fix may cause more pressure to the developer and maintainer of the plugin causing "open source" burn out (which is a known phenonema).

**Describe the solution you'd like**

After reaching again stability with 1.1 the development may split into main with tested and bug-free features which will be downloaded by Obsidian and the beta branch where people may test new functionalities and find bugs. New features may be merged into the main branch after a  specific period of time or when users with different setup/OSes test them.

Obsidian used to release new features every week, something like sprint cycles.
Having two branches, stable-production with the possibility to add fixes and experimental with new features allow minimizing the risk of introducing bugs.

**Describe alternatives you've considered**

The development process will stay as it is if the core functionality is already present and the developer doesn't plan to release often new releases with new features.

However, maintaining two branches may be perceived as additional and unneeded work.

**Additional context**

**Comment by vslinko** [comment]
@danieltomasz Thank your for your support.
Looks like I'm on a little dopamine addiction because of fast achievements and I know that it isn't good for a long term :)
I'm going to slow down a little bit after 1.1 release.
Also more tests should make plugin more stable #5

It's good idea to make beta branch but I don't know how to distribute it and how to collect feedback.
I don't want to push everyone to manual update every single time.

**Comment by danieltomasz** [comment]
The simplest way is to have specific branches for specific big potentially disrupting changes and features https://github.com/delashum/obsidian-checklist-plugin/tree/master as an example,  while the smaller fixes could be committed directly to main. 

After several users interested in the feature tested it,  the feature may be merged or rebased to main and released to the general public. Before release users may manually download it (I wonder if you could make pre-releases from non-main that are ignored by obsidian?).

Maybe I am overcomplicating things :) Maybe one branch but just waiting a day for a person who requested a feature to download manually files and test it on their computer and confirm it works? As you said after 1.1 release and test plugin will be more stable.

I could volunteer for testing on Linux.
I wonder if changes related to https://github.com/vslinko/obsidian-outliner/issues/7 maybe potentially disrupting that they need testing?

**Comment by vslinko** [comment]
@danieltomasz Yes, #7 can be buggy, so I started a branch https://github.com/vslinko/obsidian-outliner/tree/obsidian-commands :)

**Comment by danieltomasz** [comment]
You may tag me here  when you want me to test  it on Linux

**Comment by vslinko** [comment]
I'm closing the issue since I got the message :)

**Comment by vslinko** [comment]
@danieltomasz I made keybindings configurable and I need feedback.
Please install beta1 https://github.com/vslinko/obsidian-outliner/releases/tag/obsidian-commands-1 and add your comments in PR #34

**Comment by vslinko** [comment]
@danieltomasz btw it should work only with Insider build 0.11.10

**Comment by danieltomasz** [comment]
@vslinko unfortunately I am still on 0.11.9 :(

**Comment by vslinko** [comment]
@danieltomasz 0.11.13 was released!

**Comment by danieltomasz** [comment]
@vslinko noted :)  I am installing the build!

**Comment by danieltomasz** [comment]
@vslinko In latest release there is probably present  really critical error, I cannot open any note with plugin active, what I got
![image](https://user-images.githubusercontent.com/7980381/114096174-a71f8100-98be-11eb-97cd-1a0d7535f83f.png)

**Comment by danieltomasz** [comment]
@vslinko I see I added new release with the error probably mitigated

**Comment by vslinko** [comment]
@danieltomasz so now it’s ok?

**Comment by danieltomasz** [comment]
yes, it work ok! I dont have time to test everything, but I will be using version latest version on daily  basis
