### ISSUE TITLE
[BUG] Plugin line click actions not working at all

### ISSUE THREAD

**Issue by raisabelatrix** [vslinko/obsidian-outliner#320]
**Describe the bug**
Plugin's vertical indentation line click action settings don't work at all. I've turned off all other plugins except for some core ones and switched to the default theme, but it still doesn't work

**To Reproduce**
1. Install Outliner and keep default settings
2. Go to note with list
3. Click on line indentation

**Expected behavior**
The list to fold or zoom upon line click, depending on the setting

**Video**
https://user-images.githubusercontent.com/82343091/168916105-e41026ac-3e14-4e44-9d2f-4c3c913b911d.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version: 0.14.6

**Additional context**
The plugin hotkeys still work. Just the line click actions aren't doing anything

**Comment by tillmanjex** [comment]
Obsidian Zoom (in obsidian community plugins titled simply "Zoom") is required for this functionality. This is mentioned at the top of Outliners readme.
It's not built in to Outliner itself. 
Have you also installed Zoom?

**Comment by vslinko** [comment]
@raisabelatrix thanks for the feedback! I can't reproduce the problem. As @tillmanjex suggested, can you check that Zoom plugin is installed?

**Comment by raisabelatrix** [comment]
Aah I no longer use this plugin, and I've actually forgotten I made this issue. But if you think the problem's no longer there, then I'll try the plugin later. Much thanks!
