### ISSUE TITLE
Outliner needs some update to work with Obsidian 0.15.x/CM 6.0

### ISSUE THREAD

**Issue by WhiteNoiseDev** [vslinko/obsidian-outliner#323]
See announcement:

https://forum.obsidian.md/t/plugin-developers-codemirror-6-migration-guide-for-v6-0/38947

**Comment by pcuellar** [comment]
Probably related to this, here is a screenshot of the specific error I am seeing
<img width="556" alt="Screen Shot 2022-06-19 at 10 09 53 AM" src="https://user-images.githubusercontent.com/20482146/174487813-4ecf5926-9712-45c6-9e23-bac0070ae8fc.png">
