### ISSUE TITLE
[BUG] hotkeys does not work 

### ISSUE THREAD

**Issue by yongam77** [vslinko/obsidian-outliner#328]
I have installed the outliner, but when I tried to move lists and sublists up and down on my MacBook, the hotkeys of outliers did not work as intended. Instead of moving lists up or down, it just highlights all the text above or below the selected cursor. Can anyone solve this problem? Please.

**Comment by vslinko** [comment]
There was a bug https://github.com/vslinko/obsidian-outliner/issues/325
Please downgrade the plugin. Copy `main.js` `styles.css` and `manifest.json` from [2.2.5](https://github.com/vslinko/obsidian-outliner/releases/tag/2.2.5) to the `.obsidian/plugins/obsidian-outliner` folder in your vault.
