### ISSUE TITLE
[BUG] Outliner stopped working (Uncaught TypeError: language.foldedRanges is not a function)

### ISSUE THREAD

**Issue by charlesroper** [vslinko/obsidian-outliner#331]
**Describe the bug**
Outliner appears to be broken. Any action involving Outliner, whether that be simply moving the cursor into a list, or running a command like move list and sublists up and down, does not work and generates the following error in the console:

![image](https://user-images.githubusercontent.com/176/176663700-31bbbe15-312c-45b6-8e50-44989085506f.png)

It looks like I am not the only one to experience this problem. See:

https://forum.obsidian.md/t/auto-listing-bulleted-numbered-does-not-work-when-using-outliner-plugin/39474

I have tried installing and activating Outliner as the only plugin in the Obsidian Help vault and it seems to work fine there.

I have tried disabling all plugins other than Outliner in the vault I am having problems in, but I still see the same errors. Only disabling Outliner stops the errors.

**To Reproduce**
Steps to reproduce the behaviour:
1. Activate Outliner and enable debug mode
2. Place cursor in a list or run an Outliner command
3. Open console

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version: 0.14.15

**Comment by cocofoco** [comment]
I am also experiencing the same problem.

See message on the Obsidian Server on Discord:
https://discord.com/channels/686053708261228577/707816848615407697/991062842427977848

**Comment by omerdn1** [comment]
Same issue here too! Has anyone figured out a workaround?

**Comment by charlesroper** [comment]
@omerdn1 Other than disabling Outliner, no.

**Comment by omerdn1** [comment]
@charlesroper My temporary solution was to manually downgrade to 2.2.5 (replace 2.3 styles, manifest and main files with 2.2.5).

Better than disabling :) Hope it helps

**Comment by vslinko** [comment]
Thank you all for the feedback!

This problem should be fixed in the latest version of the Obisidian and the plugin. Please create a new issue if it still exists.
