### ISSUE TITLE
[BUG] "Open link under cursor" command doesn't work when the cursor is at the beginning of the list item

### ISSUE THREAD

**Issue by Glint-Eye** [vslinko/obsidian-outliner#333]
**Describe the bug**
The Open Link under cursor command doesn't work, when list item only consists of a wiki link und cursor is at the very beginning of the list item

- create list
- insert wiki link into list item at the beginning of that list item
- move cursor to beginning of list item
- try using Open Link under cursor command
- you have to move the cursor one character to the right for the command to work

**Expected behavior**

Command should open link. Works with Outliner plugin deactivated

**Desktop (please complete the following information):**
 - Obsidian 0.14.15 AppImage

**Comment by vslinko** [comment]
@Glint-Eye thank you for the feedback.

I can' t reproduce the issue. "Open link under cursor" does not work in this scenario, even if the Outliner plugin is deactivated.
