### ISSUE TITLE
[BUG] A bug with "Enhance the tab key"

### ISSUE THREAD

**Issue by user30535** [vslinko/obsidian-outliner#335]
When "Enhance the tab key" is turned on, type the following code

```
1. a
	1. b
	2. c
```

Shift+tab the "b" line, and then tab again, the expected result is that the list does not change, but the actual result is the b line and the c line get swapped:

![image](https://user-images.githubusercontent.com/108653772/178238006-70d67583-db5a-4bf9-9287-21b2002a9b58.png)

See the following screen recording:

https://user-images.githubusercontent.com/108653772/178237335-2f80b452-35b9-44ba-bd5b-a973b3d1c555.mp4

**Comment by vslinko** [comment]
@user30535 thanks for the feedback. This is expected behavior for outliners like this. You can check how it works in Roam Research or Logseq.

![Screen Recording 2022-08-07 at 11 53 14 mov](https://user-images.githubusercontent.com/205823/183283152-9963a34d-0730-488e-957c-f4d300f7da4b.gif)
