### ISSUE TITLE
[BUG] Vertical lines didn't aline at the bullet

### ISSUE THREAD

**Issue by ycbrd** [vslinko/obsidian-outliner#341]
**To Reproduce**
type as below

**Screenshots**
![image](https://user-images.githubusercontent.com/105804326/182376310-edb5edbe-5a91-4bf1-8fba-cd59ba4cc2e2.png)

**Expected behavior**
like the following
![image](https://user-images.githubusercontent.com/105804326/182377187-8f033413-62f6-43ab-a770-7f4751a193d5.png)

**Desktop:**
 - OS: windows 10 21H2
 - Obsidian Version: 15.0.6
 - plugin version: 2.3.0

**other context**
- system scaling：250%
- obsidian font size：17

**Comment by Fyzu** [comment]
Will be fixed in #365

**Comment by bukhtiyarov-a-v** [comment]
I can confirm it works after last PR mentioned in https://github.com/vslinko/obsidian-outliner/issues/341#issuecomment-1282294501
