### ISSUE TITLE
Getting unable to fold because folding is disabled when folding is enabled.

### ISSUE THREAD

**Issue by Banesmagic** [vslinko/obsidian-outliner#347]
<img width="310" alt="CleanShot 2022-08-22 at 10 04 20@2x" src="https://user-images.githubusercontent.com/35113388/185940783-e4abfa65-0643-4926-b4db-62142fc447fd.png">
<img width="741" alt="CleanShot 2022-08-22 at 10 06 19@2x" src="https://user-images.githubusercontent.com/35113388/185940975-eaa57798-4c7b-4d7c-98e9-4f86c6fbb502.png">

**Comment by stephenalandavis** [comment]
Hello,

When I turned toggled this setting on and off it started working for me.

**Comment by vslinko** [comment]
@Banesmagic @stephenalandavis Thank you for the feedback. Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/3.0.0
