### ISSUE TITLE
[BUG] Vertical line features not working

### ISSUE THREAD

**Issue by branchm** [vslinko/obsidian-outliner#348]
**Describe the bug**
Obsidian Windows v0.15.9.  Outliner Plugin v2.4.0
Hotkeys work and I see the plugin options.
But, I don't see the vertical lines working as shown in the demo (they are enabled in the settings). If I put my mouse on the "standard" vertical lines, they don't get larger like in the demo and nothing happens if I click on the (standard) vertical line.

**To Reproduce**
make a list
mouse over a vertical line
nothing happens

**Expected behavior**
vertical line gets thick and clickable as in the demo

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Obsidian Version: v0.15.9

**Additional context**

**Comment by vslinko** [comment]
@branchm Thank you for the feedback. Unfortunately, I can' t reproduce the issue. Could you please check that vertical lines are configured properly?

**Comment by branchm** [comment]
Oh sorry.  I see the issue.  I was using a non-default theme.  When I go back to the Obsidian default theme, it behaves as expected.  I see that you note that these enhancements may not work with non-default themes.
