### ISSUE TITLE
[BUG] Change defaults to avoid conflicts

### ISSUE THREAD

**Issue by WhiteNoiseDev** [vslinko/obsidian-outliner#349]
We are getting several reports that boil down to incompatibility with outliner.

I strongly encourage you to remove or at least disable by default these two options:

![image](https://user-images.githubusercontent.com/3163647/186519837-cd8d70c4-a4e7-4ab1-b956-9cf5a887fa71.png)

**Comment by vslinko** [comment]
@WhiteNoiseDev Thank you for the feedback. I'll make those options disabled by default.

**Comment by vslinko** [comment]
@WhiteNoiseDev Should be changed in https://github.com/vslinko/obsidian-outliner/releases/tag/3.0.0
