### ISSUE TITLE
[FEAT] Minor suggestion: rename plugin to "Outliner" 

### ISSUE THREAD

**Issue by ShreyasKallingal** [vslinko/obsidian-outliner#35]
Instead of calling it the "Obsidian Outliner Plugin" in the settings menu and command palette, I think it would be cleaner to just call it "Outliner." This would follow the naming convention of most other plugins I have installed. Thank you for all your hard work!

**Comment by vslinko** [comment]
@ShreyasKallingal Thank you for your contribution! Changed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.0.23
