### ISSUE TITLE
broken imported roam lists - help!

### ISSUE THREAD

**Issue by fightme-cmd** [vslinko/obsidian-outliner#352]
There is some mystery problem with all the imported roam lists in my vault.
The (native) vertical indentation guides misalign slightly (see screenshot lines 6-7) *but also* Outliner doesn't work on them!

See test screenshot below and attached file - the blocks are identical (?) but the two block lists behave different—Outliner only works for the bottom one? What gives?

Can anyone help me? I'm baffled.

![72c62cd6f14583812939e42e260100bc8350a4b0_2_625x500](https://user-images.githubusercontent.com/80396935/187022181-6db622a2-44a4-440a-9a23-dfe606d0ec77.png)

[test (1).md](https://github.com/vslinko/obsidian-outliner/files/9437572/test.1.md)

Things I have tried
- disabled all theme and plugins (obviously).
- turned (obsidian) indentation setting off and on again
- find and replaced the “ -” spacing in the document to be exactly what obsidian itself produces

**Comment by fightme-cmd** [comment]
Forgot to attach the logs! 

parseList Unable to parse list: expected indent "T", got "S"
What do T and S mean? I can't find anything on the interwebs. 

[obsidian.md-1661591696570.log](https://github.com/vslinko/obsidian-outliner/files/9437633/obsidian.md-1661591696570.log)

**Comment by vslinko** [comment]
@fightme-cmd Thank you for the feedback.

Yes, it's not clear at all. "T" means tab, "S" means whitespace.

Your document contains a mix of tabs and whitespaces. The plugin can't handle that.

To fix the issue you can convert everything to a single format.

<img width="867" alt="Screenshot 2022-08-29 at 10 21 22" src="https://user-images.githubusercontent.com/205823/187146912-0eacaad7-cec3-463b-98bf-5c4fb8b68499.png">

**Comment by csss1234** [comment]
Solution: https://github.com/vslinko/obsidian-outliner/discussions/485#discussion-5691533
