### ISSUE TITLE
Obsidian 0.16 Implements the HOME behavior natively

### ISSUE THREAD

**Issue by WhiteNoiseDev** [vslinko/obsidian-outliner#353]
FYI: https://forum.obsidian.md/t/lists-make-home-move-the-cursor-after-the-list-marker/39989

**Comment by vslinko** [comment]
@WhiteNoiseDev thanks for the feedback!

I tested it with the Outliner plugin enabled. It seems to work fine.

But I noticed that this new feature only supports the HOME button, but does not support CMD+ArrowLeft and CMD+Shift+ArrowLeft on Mac. Please consider supporting these hotkeys.
