### ISSUE TITLE
[FEAT] hope to click on the bullet to enter the child node

### ISSUE THREAD

**Issue by 5eagull** [vslinko/obsidian-outliner#36]
**hope to click on the bullet to enter the child node**

![image](https://user-images.githubusercontent.com/69051504/113006962-62059b80-91a8-11eb-9cf9-5dd83103cf86.png)

**Comment by vslinko** [comment]
Released in https://github.com/vslinko/obsidian-outliner/releases/tag/1.1.4

**Comment by omerdn1** [comment]
> Released in https://github.com/vslinko/obsidian-outliner/releases/tag/1.1.4

Thanks 👏
Would be neat to have the same functionality in preview mode as well :)

**Comment by vslinko** [comment]
@omerdn1 You can [create a discussion](https://github.com/vslinko/obsidian-outliner/discussions/categories/ideas) about your idea and may be it will be released sometime :)
