### ISSUE TITLE
[BUG] Adding a space at the bottom of an outline disables the ability to move lists and sublists

### ISSUE THREAD

**Issue by mdrain** [vslinko/obsidian-outliner#368]
**Describe the bug**
Moving lists and sublists up and down does not work if the line immediately following the outline starts with a space.

**Expected behavior**
I don't know if this is intended behavior or not, but it was unexpected.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Obsidian Version: 1.0.2

**Comment by Fyzu** [comment]
Can you attach an example file?

**Comment by mdrain** [comment]
Below is a demo. It appears that the issue only occurs when there is one top-level bullet.

![2022-10-23_13-51-29](https://user-images.githubusercontent.com/24597626/197407792-9cdc0fee-3834-4f6e-bb8e-7a9658c9879e.gif)

**Comment by Fyzu** [comment]
I think coz the empty bullet at the end is not a valid item 🤔
You also can't add a new one if the last item is empty
