### ISSUE TITLE
[BUG] Enter-key enhancement does not work in obsidan 1.0.3

### ISSUE THREAD

**Issue by vlitvin** [vslinko/obsidian-outliner#375]
**Describe the bug**
Enter-key enhancement (create task/checkbox on cmd-enter) does not work after obsidian 1.0.0 release

**To Reproduce**
1. Create new note
2. Use shortcut cmd-enter
3. Nothing happens

**Expected behavior**
After hitting cmd-enter new checkbox "- [ ]" get inserted at the beginning of the line

**Desktop (please complete the following information):**
 - OS: MacOS
 - Obsidian Version: 1.0.3
 - Outliner Version: 4.1.1

**Comment by Quorafind** [comment]
`Obsidian-Outliner` plugin did not provide this feature, it is powered by Obsidian itself. The default hotkey has been changed to `Cmd+L` in latest version of Obsidian.

**Comment by vslinko** [comment]
@vlitvin thank you for the feedback. @Quorafind is right, it's Obsidian's feature.
