### ISSUE TITLE
[FEAT]Soft line break

### ISSUE THREAD

**Issue by 5eagull** [vslinko/obsidian-outliner#38]
![image](https://user-images.githubusercontent.com/69051504/113035430-d00c8b80-91c5-11eb-8b99-2e51165d4426.png)

`Shift-Enter`   Soft line break
Newline but does not generate new bullets

**Comment by danieltomasz** [comment]
Example in Markdown
```
 * A
          * B
            BBB
          * C
```

**Comment by vslinko** [comment]
Ref https://github.com/vslinko/obsidian-outliner/discussions/52

**Comment by vslinko** [comment]
@5eagull @danieltomasz and everyone else!

After a lot of work, I finally released the first beta version of soft line break support!

I am looking for beta testers for this version. Please download [the beta version](https://github.com/vslinko/obsidian-outliner/releases/tag/1.2.0-beta1) and [report your feedback](https://github.com/vslinko/obsidian-outliner/issues/38).

**Comment by vslinko** [comment]
![out](https://user-images.githubusercontent.com/205823/119222374-cb48c180-bafc-11eb-9bd4-98e433b28c8f.gif)

**Comment by danieltomasz** [comment]
Great! Good news! I copied the beta plugin files, it works with Enter + Shift,  but it still shows me 1.1.12 release number

**Comment by vslinko** [comment]
@danieltomasz it’s okay

**Comment by Bennett-Yang** [comment]
I didn't find any problem so far. I just have an suggestion: will it be better if you remove the indent before blockquotes? It seems that you indent blockquotes with 4 spaces, which makes it align to the next-level bullet. I think it may be a little confusing.

![](https://pic.imgdb.cn/item/60a9be6835c5199ba7e305e9.jpg)

**Comment by Bennett-Yang** [comment]
I'm really glad to hear the update by the way

**Comment by danieltomasz** [comment]
> I didn't find any problem so far. I just have an suggestion: will it be better if you remove the indent before blockquotes? It seems that you indent blockquotes with 4 spaces, which makes it align to the next-level bullet. I think it may be a little confusing.
> 
> ![image.png](https://camo.githubusercontent.com/f27424eaaacd01ab707e73d8514e1923de41d2d872ef3139d76d0dd11ad3b059/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30352f32332f4c336a763279394e705247446b55622e706e67)

I think this is in general how the quotes are handled by CSS in Obsidian and it is not  something caused by plugin;
Maybe it would be good to have toggle in setting for changing CSS for quotes, I dont know if is possible that change only affect quotes in soft line break, in worst case there the CSS may  affect all quotes and I dont know how many  would expect that

**Comment by Bennett-Yang** [comment]
> > I didn't find any problem so far. I just have an suggestion: will it be better if you remove the indent before blockquotes? It seems that you indent blockquotes with 4 spaces, which makes it align to the next-level bullet. I think it may be a little confusing.
> > ![image.png](https://camo.githubusercontent.com/f27424eaaacd01ab707e73d8514e1923de41d2d872ef3139d76d0dd11ad3b059/68747470733a2f2f692e6c6f6c692e6e65742f323032312f30352f32332f4c336a763279394e705247446b55622e706e67)
> 
> I think this is in general how the quotes are handled by CSS in Obsidian and it is not something caused by plugin;
> Maybe it would be good to have toggle in setting for changing CSS for quotes, I dont know if is possible that change only affect quotes in soft line break, in worst case there the CSS may affect all quotes and I dont know how many would expect that

I rarely use blockquotes so I just realized the blockquotes are intended even if I don't use bullet list. Now I think it's okay to keep it that way. Thank you!

**Comment by danieltomasz** [comment]
@vslinko  I obseved weird behaviour, I have this in outline in my vault(I removed some personal notes, but the structure of the outline is the same), I cannot outdent the last bullet point (I am using Outliner 1.2)
```
- Thinking in Systems
	-  Line 1
		- LIne 2
	- Line 3
	- Nie m liniowych systemow
		
	- Random link from Internet
		[Swasthi's Recipes - Indian food blog with easy Indian recipes](https://www.indianhealthyrecipes.com/)
	- Cannot move this line with Tab + Shift
```

**Comment by vslinko** [comment]
@danieltomasz thank you for your feedback. I’ve already released it. Could you please create new issue.

**Comment by danieltomasz** [comment]
Done!
