### ISSUE TITLE
[BUG] freeze mouse position competely after open“ stick the cursor to the content ”option in 0.15.9

### ISSUE THREAD

**Issue by Ravenclawer** [vslinko/obsidian-outliner#385]
**Describe the bug**
open the stick the cursor to the content option in outliner plugin， back to your note and you'll find that the mouse cursor cannot be moved by clicking the left button of your mouse anymore 
**To Reproduce**
open the stick the cursor to the content option in outliner plugin， back to your note and you'll find that the mouse cursor cannot be moved by clicking the left button of your mouse anymore 
**Expected behavior**
open the  stick the cursor to the content option don't affect mouse in the entire note 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows
 - Obsidian Version: [e.g. 22] 0.15.9

**Additional context**

**Comment by vslinko** [comment]
@Ravenclawer hi
Unfortunately, I cannot reproduce the issue. Could you please update Obsidian and Obsidian Outliner to the latest versions and check again.
