### ISSUE TITLE
Unable to use the Cntl + Shit + Up/down arrows to move lists in particular notes[BUG]

### ISSUE THREAD

**Issue by sammychambers** [vslinko/obsidian-outliner#388]
**Describe the bug**
I am unable to use the ctrl + shift + up/down arrow in certain notes to move lists up and down while it works fine in other notes. 

**To Reproduce**
1. I create a new  note and create a list as shown in the screen recorder. Moving the list works fine.
2. When I try to do the same on my other document it doesn't work.
3. Yet when I copy that same data from the second note into the first note it does allow me to move the lists up and down

**Expected behavior**
I expect to be able to use the ctrl + shift + up/down arrow commands to move lists up and down.

**Screenshots**
https://drive.google.com/file/d/1ySQWhzP163R_6dRi_NeQW5N78jEPDINN/view

**Desktop (please complete the following information):**
 - OS: Windows
 - Obsidian Version: 1.0.3

**Additional context**

**Comment by vslinko** [comment]
@sammychambers Thank you for your feedback.

The plugin is very strict about list line indents. If you have mixed up tabs/spaces or the wrong number of tabs/spaces, it will break the entire list.

Currently the plugin can't help identify the problem, but I have that [idea](https://github.com/vslinko/obsidian-outliner/issues/395) in the plans.
