### ISSUE TITLE
[BUG/FEAT] Editing the same note  in splited pane destroy focus (Cmd/Ctrt + .)

### ISSUE THREAD

**Issue by danieltomasz** [vslinko/obsidian-outliner#39]
**Describe the bug**
Editing the same note  in  a split pane destroy focus (same as I would use Cmd/Ctrt + Shift +  .)
**To Reproduce**
-  Create List
```
- A
	- B
		- C
```
- Open note in split Pane. 
 - Use hotkey CTR;+. to open leaf in focus
 - Editing  note in other panes will destroy  focus  (same  effect as I would use Cmd/Ctrt + Shift +  .)

**Expected behaviour**

Editing note outside of focus (at least when the edited lines in the second pane doesn't modify the position of the focused text in the file) should not break the focus. I don't know if this is possible so I put in a bug/feature label/.

**Screenshots**
![Peek 2021-03-30 20-14](https://user-images.githubusercontent.com/7980381/113036940-21e8ed80-9195-11eb-8516-d7bff2e59a71.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] LInuxOS
 - Obsidian Version: [e.g. 22] 0.11.9

**Additional context**

**Comment by vslinko** [comment]
@danieltomasz Thank you for your contribution! Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.0.20

**Comment by danieltomasz** [comment]
It works, thanks!
