### ISSUE TITLE
Support for mixed ordered/unordered lists

### ISSUE THREAD

**Issue by Cito** [vslinko/obsidian-outliner#390]
It seems when the outliner plugin is activated, I cannot enter structures like this:

```
- unordered item
- ordered sublist:
  1. ordered item
  2. ordered item
  3. ordered item
- unordered item
```

or 

```
1. ordered item
2. unordered sublist:
  - unordered item
  - unordered item
  - unordered item
3. ordered item
```

When I want to create the differently styled sublist, the plugin does not let me remove the bullet point and replace it with a number or vice versa.

Is this expected? Are all sublists supposed to have the same style (ordered/unordered)? Or am I missing something?

**Comment by Cito** [comment]
Sorry, the bug label was added automatically. Currently not sure if this is a bug or a feature :)

**Comment by vslinko** [comment]
@Cito Thank you for your feedback.

The plugin should work properly with mixed lists.

https://user-images.githubusercontent.com/205823/204483451-b3cadc17-2972-4d25-a911-0ad1f5106b2f.mov

If it doesn't, please upload the affected file.

**Comment by Cito** [comment]
Hi @vslinko - that's good to hear. In fact I can move items in mixed lists. My question was more about how I can *enter* sublists. Since when you create a new sublist with Enter+Tab, then a sublist of the same type as the parent list is created automatically, and if you try to remove the bullet point or the number of the sublist with Backspace, then the whole line is removed and the cursor is in the parent list again.

But I think I found how you can do it now: It is possible to select the bullet point (or number) together with the following space, then you can enter a number (or bullet point) followed by a space to change the type of the sublist.

Note that this is different from the behavior without the plugin, were you can remove the bullet point simply by hitting Backspace.

Another way of changing the list style is to use the "toggle numbered/bulleted list" command which I also discovered only now. Maybe it would be good to have a "toggle list style" command that would toggle between numbered and bulleted (and maybe normal in a three-state toggle). Then I would only need one keyboard shortcut for changing the list style instead of two.

Another thing that makes it difficult to work with mixed lists is that when you enter a sublist and then press unindent, then the bullet point of the item is not adapted to the style of the parent list, it stays the same style as the sublist. But that's also the case without the plugin. Again, the three-way-toggle mentioned above could help with that.

**Comment by vslinko** [comment]
Hi @Cito 

> Maybe it would be good to have a "toggle list style" command that would toggle between numbered and bulleted (and maybe normal in a three-state toggle). Then I would only need one keyboard shortcut for changing the list style instead of two.

You can use another plugin that have such shortcut  https://github.com/argenos/hotkeysplus-obsidian

> Another thing that makes it difficult to work with mixed lists is that when you enter a sublist and then press unindent, then the bullet point of the item is not adapted to the style of the parent list, it stays the same style as the sublist. But that's also the case without the plugin. Again, the three-way-toggle mentioned above could help with that.

That's interesting. Could you please create a feature request about unindenting different list types. https://github.com/vslinko/obsidian-outliner/discussions/categories/ideas

**Comment by Cito** [comment]
> You can use [another plugin](https://github.com/argenos/hotkeysplus-obsidian) that has such shortcut.

Thanks, indeed, it provides exactly that 3-way-toggle for list styles. There seems to be a plugin for everything. Which is great except that managing that flea circus of plugins for multiple vaults can be a pain.

> Could you please create a feature request about unindenting different list types

Will do so. Thanks for providing this useful plugin and your quick replies!
