### ISSUE TITLE
Ctrl+Shift+Up no longer works to move item up 

### ISSUE THREAD

**Issue by LeslieP-TX** [vslinko/obsidian-outliner#398]
Outliner plugin v4.1.1
Obsidian v1.0.3

Have tested with all plugins disabled except this one and using default template.

ctrl+shift+up moves a standard bullet item, will not move a bullet item in an outline, either at top level or any subsidiary levels

**Comment by vslinko** [comment]
@LeslieP-TX thank you for the feedback. 

I can't reproduce the issue. could you please make a screen recording.

**Comment by khanhtoan529** [comment]
> @LeslieP-TX thank you for the feedback.
> 
> I can't reproduce the issue. could you please make a screen recording.

Same issue here. 
Reproduce the issue:
1. Create a list (3+ item)
2. Ctrl + Shift + Down is fine. It moves the item down. But Ctrl+Shift+Up, nothing happen.

Same with Ctrl+Down will unfold the list, but Ctrl+Up won't

**Comment by khanhtoan529** [comment]
@vslinko is there any update?

**Comment by jeongsik74** [comment]
I've seen cases where it doesn't work properly if a character other than the tab character, such as a space, is put in front of the bullet(-). If even one of the documents has such a place, list up/down will not work for the entire document. 
In this case, **deleting all other characters besides the tab character before the bullet(-)** works fine.

**Comment by khanhtoan529** [comment]
I changed the shortcut to another binding, e.g., Alt+Up, and it works. That's weird.

**Comment by ChristopherConnock** [comment]
@khanhtoan529 that makes sense - this was the case for me.
![image](https://user-images.githubusercontent.com/1145313/217615184-148fa0f7-6f29-49d3-94e7-0e40dc9f65c2.png)

**Comment by vslinko** [comment]
It seems according to the thread there are some workarounds. Closing the issue. If the problem persists, please create a new issue.
