### ISSUE TITLE
[BUG]Error with `Cmd-Shift-ArrowUp/ArrowDown`

### ISSUE THREAD

**Issue by lll637637** [vslinko/obsidian-outliner#40]
![image](https://user-images.githubusercontent.com/69051504/113086247-dfb2c100-9213-11eb-9034-65d135b062fb.png)

The cursor is behind the `···` symbol , Use the shortcut key `Cmd-Shift-ArrowUp/ArrowDown` will cause an error . 

![image](https://user-images.githubusercontent.com/69051504/113086735-d1b17000-9214-11eb-8169-f57624af7074.png)

Cursor is behind `C`
It is correct to use the shortcut key `Cmd-Shift-ArrowUp/ArrowDown`

**Comment by vslinko** [comment]
@lll637637 Thank you for your contribution!

Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.0.22

I disabled putting the cursor after `...` sign.
