### ISSUE TITLE
[BUG] Wrong mouse position when entering [[ in the list

### ISSUE THREAD

**Issue by Miroier** [vslinko/obsidian-outliner#402]
**Describe the bug**
Wrong mouse position when entering [[ in the list

**To Reproduce**
enter [[ in list

**Expected behavior**
The mouse positoin should be in the middle like this: [[|]].
But if I entering [[ in list with outliner-plugin on. the result is: [[]|]. Meanwhile, i cannot move the mouse position left.
I think the problem is in the plugin because error does not occur with the plugin off.

**Screenshots**
![outliner](https://user-images.githubusercontent.com/45321964/208459453-ace7f95f-aa23-4a2c-9bd1-8e925a4515db.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Obsidian Version: 1.0.3
 - Outliner Versoin: 4.2.0

**Comment by lamdor** [comment]
I also just started running into this after the update to 4.2.0.

**Comment by vslinko** [comment]
@Miroier @lamdor thank you for the feedback

@sitaktif it looks like it's because of https://github.com/vslinko/obsidian-outliner/pull/401. it would be great if you could fix it today. if not, i'll fix it.

**Comment by vslinko** [comment]
Added a broken test to the main branch

**Comment by sitaktif** [comment]
I see what’s going on, I’ll submit the (straightforward) fix as soon as I can sit in front of my computer (hopefully in the next hour).

**Comment by vslinko** [comment]
`Cmd-a` is also broken. Looks like `getContentStartCh` should include `checkboxLength`. But this change is potentially very dangerous and it needs to be refactored very carefully.

**Comment by sitaktif** [comment]
In light of your last two comments, maybe we should we revert the change.

**Comment by sitaktif** [comment]
Actually https://github.com/vslinko/obsidian-outliner/issues/402#issuecomment-1358220450 was addressed, and https://github.com/vslinko/obsidian-outliner/issues/402#issuecomment-1358236978 is not a regression, so maybe the right way is forwards!

**Comment by vslinko** [comment]
Fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/4.2.1
