### ISSUE TITLE
[BUG] bad position of cursor when using option "stick cursor to content

### ISSUE THREAD

**Issue by cvh-obsi** [vslinko/obsidian-outliner#409]
**Describe the bug**
when I type a list then a link [[]], the cursor is placed after first closing square bracket
like this [[] | ] , where | is the pace of the cursor

**To Reproduce**
disabling this option supress the problem

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Obsidian Version: [e.g. 22]

**Additional context**

**Comment by vslinko** [comment]
@cvh-obsi thank you for the feedback.
Unable to reproduce on version 4.3.0. Could you please update to version 4.3.0 and check again.
