### ISSUE TITLE
Move to Next/Previous Parent

### ISSUE THREAD

**Issue by caseywatts** [vslinko/obsidian-outliner#415]
I'm thinking about adding a command to move an item up/down by parent group. Would that be welcome? :)

so for example:
```
- Done
  - Completed Task A
- To Do
  - Large Task A
  - Small Task B << cursor on this line when "move to previous parent" command is pressed
  - Small Task C
```

becomes
```
- Done
  - Completed Task A
  - Small Task B << cursor on this line which has moved
- To Do
  - Large Task A
  - Small Task C
```

I can kinda see how I would do it, this api looks easy to interact with!
https://github.com/vslinko/obsidian-outliner/blob/dfe5446f63353fe79f41cce28cb6f63a43625e96/src/operations/MoveUpOperation.ts#L31

**Comment by vslinko** [comment]
@caseywatts Hi! 
Yes, I think this functionality is good to be included in the plugin. I don't have documentation for contributors, please try to figure it out on your own. I'll give feedback on the pull request. It is better to start by writing tests.

**Comment by vslinko** [comment]
Closing the issue and waiting for a pull request :)
