### ISSUE TITLE
Outliner adds a little overhead on latency for big enough lists

### ISSUE THREAD

**Issue by stasbel** [vslinko/obsidian-outliner#425]
Plain and simple: creating new line todo with Enter produces a small but notable lag with whole Obsidian frozen.
With big enough list (around 300-400 todos total with 90% of them folded and only ~10 top-level) it feels like around 200-300ms delay.

This damage the usability of Obsidian as it's usually very swift for pretty much everything.

**Comment by vslinko** [comment]
@stasbel thank you for the feedback

I reproduced the problem. There is an inefficiency in the algorithm related to folded lists. The algorithm needs to be completely rewritten.

**Comment by vslinko** [comment]
Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/4.6.0
