### ISSUE TITLE
Heading use breaks outliner block

### ISSUE THREAD

**Issue by xBlady** [vslinko/obsidian-outliner#433]
Outliner doesn't work well with headings. I'd like to be able to use headings within outlined document structure. Right now when I select part of a outlined structure and want to make it a heading - outliner converts whole outlined block to dash based, code-like style that no logner works

**Comment by vslinko** [comment]
@xBlady I'm not sure that I understand you correctly, but Markdown doesn't support headings within lists. If you mean something else, please provide more details. For example, a screencast.
