### ISSUE TITLE
[FEAT] Zoom out to a parent node with a hotkey

### ISSUE THREAD

**Issue by demicuz** [vslinko/obsidian-outliner#45]
`Cmd-Shift-.` currently seems to zoom out of the whole list. To zoom out to parent nodes you have to click on the breadcrumbs. It would be useful to have a hotkey that zooms out to a parent node.

**Comment by vslinko** [comment]
@demicuz Thank you for your contribution!
But it's duplicate of #9
I'm closing your issue. Please follow #9 and stay tuned!
