### ISSUE TITLE
[BUG] Doesn't drag on most items 😞

### ISSUE THREAD

**Issue by yarub123** [vslinko/obsidian-outliner#454]
**Describe the bug**
Simply doesn't drag the bullet points. I recall it working fine before last Obsidian update. It does however work on SOME bullet points, super weird. 

**Screenshots**
<img width="646" alt="image" src="https://github.com/vslinko/obsidian-outliner/assets/84487964/d46fc26f-5601-4a17-aa30-23da07f24341">

**Environment (please complete the following information):**
 - OS: MacOS
 - Obsidian Version 1.3.4 (Installer 0.14.6)
 - Plugin Version: 4.7.1

**Comment by dampfwal3477** [comment]
This only happens to me if I am using a code block (until now), indenting the code block seems to be a work around (until now).

**Comment by yarub123** [comment]
@dampfwal3477 no worries, thanks for the response. (NB: this wasn't on a code block when I submitted OP).
