### ISSUE TITLE
[FEAT] Can't indent bullets after numbered lists

### ISSUE THREAD

**Issue by argenos** [vslinko/obsidian-outliner#46]
**Describe the bug**
 Can't indent bullets after numbered lists

**To Reproduce**
1. Create one item as a numbered list
2. Add a new item by pressing enter, and delete the number and change it to a bullet (or use a hotkey, like in hotkey++)
3. Try to indent the bullet to make it a child of the first numbered item

**Expected behavior**
The bullet would be indented under the numbered item

**Screenshots**
![Peek 2021-04-01 22-02](https://user-images.githubusercontent.com/5426039/113348224-9f982f00-9336-11eb-83a4-2aacf6b53fb2.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Obsidian Version: 1.0.21

**Additional context**
N/A

**Comment by vslinko** [comment]
@argenos Thank you for your contribution! Currently ordered lists are unsupported.

I'm converting this issue from `bug` to `enhancement` and putting in into `1.2.0` milestone.

**Comment by ngirard** [comment]
Just ran into this problem.
I'd undoubtedly qualify this as an issue, rather than a feature request.

Cheers, and thanks for your work !

**Comment by argenos** [comment]
This issue is getting a bit annoying (at least on version 1.1.6): So far I have been able to still use numbered and bulleted lists old-school style by tabbing the numbered list version and switching to bullets once indented. The problem now comes when I want to add a child bullet to one of the indented ones, as the parent bullet gets unindented and it's not possible to indent it again:

![Peek 2021-05-05 11-10](https://user-images.githubusercontent.com/5426039/117119584-9580aa80-ad92-11eb-9bee-7f4503585119.gif)

**Comment by vslinko** [comment]
@argenos Thank you for your contribution! Numbered lists support was released in https://github.com/vslinko/obsidian-outliner/releases/tag/1.3.0
