### ISSUE TITLE
[REQUEST] Setting to enable/disable keystroke functionality (e.g. cmd-↑)

### ISSUE THREAD

**Issue by dgodot** [vslinko/obsidian-outliner#467]
Thanks for creating this great outliner plugin for Obsidian!

It provides a number of related functionalities, and many of those functions (e.g. "Enhance the Enter key") are optional.

One function that is not optional is the keystroke-hijack functionality (e.g. to fold/unfold when pressing cmd-↑ or cmd-↓).
Since those keystrokes have other standard uses in text editing on MacOS, I'd love to be able to disable them (or even change the hotkey for them) while still keeping other functions of the plugin active.

Thanks for considering!

**Comment by vslinko** [comment]
Hi @dgodot , thank you for the feedback.
You can delete those shortcuts in Obisidian's settings to keep default behaviour.
<img width="1169" alt="Screenshot 2023-08-07 at 11 05 52" src="https://github.com/vslinko/obsidian-outliner/assets/205823/b286bc63-62cb-460e-b92a-b4d0865aea8d">

**Comment by dgodot** [comment]
Oh how perfect, thanks so much for replying!
