### ISSUE TITLE
[BUG] Strange special character breaks "move list and sublist up and down"

### ISSUE THREAD

**Issue by csss1234** [vslinko/obsidian-outliner#471]
Long time user and fan : )

I know that a leading space, for example, will cause this problem, but I found something new today. Try to use "move list and sublist up and down" on the following lines. I copy and pasted this from a website in a foreign language, I have no idea what secret hidden character is around that colon, but it breaks outline!

```
- S8347558245 
- S002360 :230
```

**Comment by vslinko** [comment]
@csss1234 Hi! thank you for the feedback.

Your example contains a `Unicode Line Separator` before `:230`, which breaks the parser.
I don't know how to fix this, other than to remove this hidden line separator, which doesn't actually separate lines.
