### ISSUE TITLE
[BUG] "Fold/unfold the list" hotkey defaults conflict with common Mac global hotkeys

### ISSUE THREAD

**Issue by evictor** [vslinko/obsidian-outliner#482]
**Describe the bug**

The default hotkeys for *Fold/unfold the list* are ⌘↑ and ⌘↓, respectively. These conflict with global Mac hotkeys (i.e., known and relied on by any ordinary Mac user) for the rather common cursor positioning commands "move (cursor) to start" and "move to end," respectively. In effect, by installing this plugin, the default hotkeys cause common hotkeys to no longer function as expected in the Obsidian text editor, which is coincidentally where this plugin's hotkeys are useful.

**To Reproduce**

1. Install the plugin on a Mac.
2. Try to use ⌘↑ or ⌘↓ hotkeys in a large text to move the cursor around.
3. No cursor movement occurs. (If you are in a list where this plugin is active, then the list may fold/unfold as a result of those hotkeys' usage.)

**Expected behavior**
The cursor moves according to Mac norms; no folding/unfolding of a list takes place.

**Environment (please complete the following information):**
 - OS: Mac

**Additional context**
The simple and probably most advisable solution is just to change the default hotkeys to something less likely to conflict with extant norms. In particular, you could just use the same shortcuts as for Windows defaults (^↑ and ^↓; that is, Ctrl instead of Cmd) and conflicts would be avoided.

**Comment by vslinko** [comment]
@evictor hi! thank you for the feedback

This is an intentionally chosen defaults. I wanted to keep the same UX for users who switched from other outliners.
You can always change hotkeys in the settings if you want to return the default behaviour.
