### ISSUE TITLE
[BUG]An error that affects normal useV1.0.23 

### ISSUE THREAD

**Issue by lll637637** [vslinko/obsidian-outliner#49]
![image](https://user-images.githubusercontent.com/69051504/113385589-ff381e00-93ba-11eb-9e4f-d27ca2975d33.png)

![33](https://user-images.githubusercontent.com/69051504/113385190-32c67880-93ba-11eb-9944-34a24a8c59c8.gif)
I am very happy to use this plugin, but I found a bug in the latest version.

**Comment by vslinko** [comment]
@lll637637 Thank you for your contribution! Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.0.24
