### ISSUE TITLE
[BUG] welcome doc on iphone can’t be closed

### ISSUE THREAD

**Issue by sylvaticuskorax** [vslinko/obsidian-outliner#513]
**Describe the bug**
after installing outliner, i opened it up to adjust settings. the doc title and the close button (x) are up below the time and battery and signal strength icons. i cannot tap the x to close the doc and force quitting the app and reopening just reopens the doc.

**To Reproduce**

1. install plugin
2. open settings > community plugins
3. tap outliner

**Expected behavior**
the document should open normally with title and close button accessible

**Screenshots**
![image](https://github.com/vslinko/obsidian-outliner/assets/71984322/4cda27a6-e826-4db3-a1af-3b1aa48672e4)

**Environment (please complete the following information):**
 - OS: iOS 17.3
 - Obsidian Version: 1.5.11
 - Plugin Version: whatever the latest is as of today. i can no longer use obsidian to get the number.

**Additional context**

**Comment by vslinko** [comment]
@sylvaticuskorax thank you for the feedback. should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/4.8.1
