### ISSUE TITLE
Make plug-in configurable 

### ISSUE THREAD

**Issue by vslinko** [vslinko/obsidian-outliner#6]

**Comment by davecan** [comment]
Request configurability of the hotkeys. And thanks for the plugin!

**Comment by danieltomasz** [comment]
If there will be a  configuration menu for the plugin could "Better lists styles" may be turned on/off from there?

**Comment by vslinko** [comment]
@danieltomasz Released in https://github.com/vslinko/obsidian-outliner/releases/tag/1.0.18

**Comment by argenos** [comment]
Another vote for configurable hotkeys!

**Comment by mdroidian** [comment]
Not sure if this should be here, or separate request but:

I'd love to be able to set Ctrl-Up, Ctrl-Down to unfold, fold headers as well!

**Comment by vslinko** [comment]
@mdroidian configurable hotkeys are under development right now. please check #34

**Comment by TWK108** [comment]
It would be great if we would also be able to configure Ctrl+Backspace to only delete the word to the left of the courser instead of the whole item content.

**Comment by vslinko** [comment]
@TWK108 please check beta release out https://github.com/vslinko/obsidian-outliner/releases/tag/obsidian-commands-2
it should work as you want
please report if it's not

**Comment by vslinko** [comment]
I just released 1.1.0-beta5 https://github.com/vslinko/obsidian-outliner/releases/tag/1.1.0-beta5

It could be the latest beta before public release.
I'm looking for beta testers for this release.
Please install 1.1.0-beta5 and report issues.
