### ISSUE TITLE
[FEAT] Work with Headings

### ISSUE THREAD

**Issue by rapatel0** [vslinko/obsidian-outliner#61]
## Desired Functionality 
- Be able to zoom in on headings 
- Be able to toggle heading folding.
- Be able to move Heading sections around

I would love the ability to move this fluidly with heading. The zooming in on a heading would also be great. Not sure how complex this would be.

**Comment by vslinko** [comment]
@rapatel0 Thank you for your contribution!

it looks related to #53 so It's better to leave your comment there and upvote the discussion.

**Comment by vslinko** [comment]
I made the new Obsidian Zoom plugin with headings support! Please check it out https://github.com/vslinko/obsidian-zoom
