### ISSUE TITLE
[BUG] Moving an item causes nearby lists to unfold

### ISSUE THREAD

**Issue by whitenoisedev** [vslinko/obsidian-outliner#62]
**Describe the bug**
Moving an item causes nearby lists to unfold

**To Reproduce**
1. Fold all items
2. Mov a sublist

**Screenshots**
![test2](https://user-images.githubusercontent.com/3163647/113634286-81834500-963c-11eb-8af0-1b25a28401af.gif)

**Desktop (please complete the following information):**
 - OS: Win10
 - Obsidian Version: 0.11.13

**Comment by vslinko** [comment]
@whitenoisedev Thank you for your contribution!

Should be fixed in beta release https://github.com/vslinko/obsidian-outliner/releases/tag/obsidian-commands-4
