### ISSUE TITLE
[BUG] Can't move the cursor to the next line with a mouse click

### ISSUE THREAD

**Issue by zhl111** [vslinko/obsidian-outliner#65]
![自发同步1](https://user-images.githubusercontent.com/29135984/113975245-cb08a580-9871-11eb-933d-52b8e64aa573.gif)
Click on the next line, but it cannot be reached

**Comment by vslinko** [comment]
@zhl111 Thank you for your contribution!

Unfortunately I can't reproduce the bug. Please check latest beta version of plugin https://github.com/vslinko/obsidian-outliner/releases/tag/obsidian-commands-3 with lates stable version of Obsidian and confirm bug still exists.

**Comment by rapatel0** [comment]
Yeah I've observed the same issue. It persists even if you disable outliner in the community plugins menu. The only two things seem to fix it:
- Restarting obsidian. 
- Toggling/Disabling themes (switching back to the default Obsidian theme) fixes it temporarily. 


Note: I've tried the following 
- Disabling vim mode
- Disabling css snippets

**Comment by rapatel0** [comment]
One more note:
When using [clutter-free](https://forum.obsidian.md/t/clutter-free-edit-mode/6791), outliner appears to stop working

I suspect there is something here as many of the community themes have clutter free css under the hood.

**Comment by vslinko** [comment]
Could you please send me a file with the problem behavior. And please check logs in chrome devtools (press Command+Option+I on Mac or Control+Shift+I on Windows/Linux)

**Comment by rapatel0** [comment]
Nothing shows up in the console.

**Comment by rapatel0** [comment]
Try enabling the california-coast theme

**Comment by zhl111** [comment]
![image](https://user-images.githubusercontent.com/29135984/114197412-e7493700-9984-11eb-96d6-f5fab9da4879.png)
theme：Blue Topaz
reproduce the bug.

**Comment by zhl111** [comment]
![test](https://user-images.githubusercontent.com/29135984/114198916-6e4adf00-9986-11eb-90af-1e3701da02ac.gif)
it‘s closed minimal Theme settings

**Comment by liaosheng1999** [comment]
me too,the same problem,so i have return to 1.0.20 version

**Comment by vslinko** [comment]
Cannot reproduce even with clutter-free or non-default themes :(

Could someone send me an archive with your Obsidian vault?
Also please send me your Obsidian version and your Outliner plugin version.

**Comment by vslinko** [comment]
@zhl111 @rapatel0 @liaosheng1999 Please try to install latest release https://github.com/vslinko/obsidian-outliner/releases/tag/1.1.0

May be it fixes the issue.

**Comment by rapatel0** [comment]
I turned off plugins and custom css, and the plugin seems to be working. I'm now turning on each plugin 1 by 1 to isolate if this was being caused by some conflict. Will report back if I isolate the issue.

**Comment by rapatel0** [comment]
Nope encountered it again. 

I think it may be related to the day planner plugin ( https://github.com/lynchjames/obsidian-day-planner). I'm now only seeing it in the day planner note

**Comment by Cateroo** [comment]
I have a similar issue on windows (outliner version 1.1.4). It doesn't happen (for me) when I turn off the "Stick the cursor to the content" option. It also seems mostly random in that the cursor will go to some bullet points but not others.  

It also doesn't happen to the second line of the same bullet point, if the bullet point is a longer paragraph with more than one line. (ie, in such cases, I can place the cursor on the second line in the bullet point, but not on the first). 

It does seem like it doesn't happen for some themes but happens with others. Changing the font in the theme doesn't affect behaviour.

**Comment by zhl111** [comment]
![test](https://user-images.githubusercontent.com/29135984/114823161-b38f6680-9df5-11eb-9981-b3604cbb4374.gif)
obsiadian v0.11.13
Enter text in the first line
Enter "-" on the second line and the problem will be reproduced

**Comment by zhl111** [comment]
![test](https://user-images.githubusercontent.com/29135984/114824070-ebe37480-9df6-11eb-9617-b7eee9e1b07e.gif)
obsiadian v0.11.13
Enter text in the first line
Enter "-" on the second line and the problem will be reproduced
 but
Once the input text is collapsed, the problem is gone

**Comment by liaosheng1999** [comment]
> Nope encountered it again.
> 
> ~I think it may be related to the day planner plugin ( https://github.com/lynchjames/obsidian-day-planner). I'm now only seeing it in the day planner note~
> 
> Edit: Nevermind. Turned off the day planner plugin and the problem persists. Specifically however with custom themes.

yes，my problem also happened at the file about Day Planner.Other files run well(plugin version 1.1.3)

**Comment by vslinko** [comment]
Still cannot reproduce :(

Could someone send me an archive with your Obsidian vault? I need `.obsidian` folder that contains all plugins and settings.

**Comment by zhl111** [comment]
[Untitled 3.md](https://github.com/vslinko/obsidian-outliner/files/6321924/Untitled.3.md)

[.obsidian.zip](https://github.com/vslinko/obsidian-outliner/files/6321927/default.obsidian.zip)

**Comment by vslinko** [comment]
Still cannot reproduce :(

![out](https://user-images.githubusercontent.com/205823/115010620-4bed2000-9eb6-11eb-8d33-25f0a7e8b3dc.gif)

Will investigate more.

**Comment by liaosheng1999** [comment]
> Still cannot reproduce :(
> 
> ![out](https://user-images.githubusercontent.com/205823/115010620-4bed2000-9eb6-11eb-8d33-25f0a7e8b3dc.gif)
> 
> Will investigate more.

maybe windows?

**Comment by rapatel0** [comment]
> I have a similar issue on windows (outliner version 1.1.4). It doesn't happen (for me) when I turn off the "Stick the cursor to the content" option. It also seems mostly random in that the cursor will go to some bullet points but not others.

I've been running with this option off for two days with no issues. Been running with themes as well.

**Comment by vslinko** [comment]
> maybe windows?

Tested on Windows and MacOS. It's working.

**Comment by zhl111** [comment]
haha，Very interesting

**Comment by Cateroo** [comment]
Here's mine: 

The issue shows up at the bullet point starting with the word "Line 2" (the others start with Lorem ipsum text) - and seems to persist in bullet points after that, when "stick the cursor to the content" is enabled. The issue doesn't show up when this is disabled. 


[Outliner Test.zip](https://github.com/vslinko/obsidian-outliner/files/6326825/Outliner.Test.zip)

**Comment by vslinko** [comment]
Still working as expected... Even on Windows and MacOS.

I can suggest where problem is could be. Could you replace `.obsidian/plugins/obsidian-outliner/main.js` with attached version and check again?

[main.js.zip](https://github.com/vslinko/obsidian-outliner/files/6327899/main.js.zip)

**Comment by zhl111** [comment]
Problem gone for now

**Comment by vslinko** [comment]
Good! So, we found out that problem was introduced in #40 and #49

I'll try to fix both problems, but I need help to test it, because I cannot reproduce it.

**Comment by vslinko** [comment]
[main.js.zip](https://github.com/vslinko/obsidian-outliner/files/6352140/main.js.zip)

Made some changes. Could you please test if it works?

If it's not please open DevTools by pressing Command+Option+I or Control+Shift+I and copy logs from the console.

**Comment by trungng2006** [comment]
> 
> 
> [main.js.zip](https://github.com/vslinko/obsidian-outliner/files/6352140/main.js.zip)
> 
> Made some changes. Could you please test if it works?
> 
> If it's not please open DevTools by pressing Command+Option+I or Control+Shift+I and copy logs from the console.

Using this main.js, this is what come up in the developer console:
cursor Pos {line: 58, ch: 3, sticky: "before", xRel: 89.193359375}
EnsureCursorInListContentFeature.ts:40 currentCoords {left: 559.806640625, right: 559.806640625, top: 637.4849208068845, bottom: 661.4751666259763}
EnsureCursorInListContentFeature.ts:45 lineStartCursor Pos {line: 57, ch: 15, sticky: "before", xRel: -135.20660400390625, outside: 1}
EnsureCursorInListContentFeature.ts:52 newCursor {line: 57, ch: 15}
EnsureCursorInListContentFeature.ts:38 cursor {line: 57, ch: 15}
EnsureCursorInListContentFeature.ts:40 currentCoords {left: 675.0132446289062, right: 675.0132446289062, top: 613.4946749877927, bottom: 637.4849208068845}
EnsureCursorInListContentFeature.ts:45 lineStartCursor Pos {line: 56, ch: 3, sticky: "before", xRel: 95.20660400390625, outside: 1}
EnsureCursorInListContentFeature.ts:52 newCursor {line: 56, ch: 3}
EnsureCursorInListContentFeature.ts:38 cursor {line: 56, ch: 3}
EnsureCursorInListContentFeature.ts:40 currentCoords {left: 559.806640625, right: 559.806640625, top: 589.5044291687009, bottom: 613.4946749877927}
EnsureCursorInListContentFeature.ts:45 lineStartCursor Pos {line: 55, ch: 1, sticky: "before", xRel: 539.806640625}
EnsureCursorInListContentFeature.ts:52 newCursor {line: 55, ch: 5}
EnsureCursorInListContentFeature.ts:38 cursor {line: 55, ch: 5}
EnsureCursorInListContentFeature.ts:40 currentCoords {left: 583.8174438476562, right: 583.8174438476562, top: 565.5141833496093, bottom: 589.5044291687011}
EnsureCursorInListContentFeature.ts:45 lineStartCursor Pos {line: 55, ch: 3, sticky: "before", xRel: 4.01080322265625}

**Comment by trungng2006** [comment]
And when I unload the plugin, it gave this error:
```
ListsStylesFeature.ts:36 Uncaught (in promise) TypeError: Cannot read property 'removeChild' of null
    at ListsStylesFeature.eval (eval at <anonymous> (app.js:1), <anonymous>:1181:46)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:26:71)
    at new Promise (<anonymous>)
    at __awaiter (eval at <anonymous> (app.js:1), <anonymous>:22:12)
    at ListsStylesFeature.unload (eval at <anonymous> (app.js:1), <anonymous>:1179:16)
    at ObsidianOutlinerPlugin.eval (eval at <anonymous> (app.js:1), <anonymous>:2076:31)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:26:71)
    at new Promise (<anonymous>)
```

**Comment by vslinko** [comment]
[main.js.zip](https://github.com/vslinko/obsidian-outliner/files/6369282/main.js.zip)

I think now it should work well. Please check.

**Comment by trungng2006** [comment]
> 
> 
> [main.js.zip](https://github.com/vslinko/obsidian-outliner/files/6369282/main.js.zip)
> 
> I think now it should work well. Please check.

This version work perfectly!

**Comment by vslinko** [comment]
Fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.1.6

Thank you all for your contributions!
