### ISSUE TITLE
Use Obsidian commands instead of CodeMirror event listeners

### ISSUE THREAD

**Issue by vslinko** [vslinko/obsidian-outliner#7]
See discussion here: https://github.com/obsidianmd/obsidian-releases/pull/212#issuecomment-804293888

**Comment by whitenoisedev** [comment]
Hi

Just wanted to let you know that since version 0.11.10, obsidian captures all keyboard events then sends them to codemirror if necessary.

**Comment by vslinko** [comment]
@whitenoisedev Thank you! I don't have insider release, so I'm waiting for public release.

**Comment by vslinko** [comment]
Is anyone uses Outliner plugin with Insider build?
I made keybindings configurable and I need feedback.
Please install beta1 https://github.com/vslinko/obsidian-outliner/releases/tag/obsidian-commands-1 and add your comments here.

**Comment by whitenoisedev** [comment]
I tested it. It looks like it's working. I will keep on using it

**Comment by danieltomasz** [comment]
I also started using it, for me it is also working

**Comment by vslinko** [comment]
I just released 1.1.0-beta5 https://github.com/vslinko/obsidian-outliner/releases/tag/1.1.0-beta5

It could be the latest beta before public release.
I'm looking for beta testers for this release.
Please install 1.1.0-beta5 and report issues.
