### ISSUE TITLE
[BUG] Top of README File (Github workflow badges) is broken

### ISSUE THREAD

**Issue by danieltomasz** [vslinko/obsidian-outliner#74]
after latest commit, if you noticed that feel free to close @vslinko
![image](https://user-images.githubusercontent.com/7980381/114419143-789df080-9bb3-11eb-9815-2c95c677b395.png)

**Comment by vslinko** [comment]
@danieltomasz thank you. I noticed that. it was something with shields.io 
Now it’s working
