### ISSUE TITLE
[BUG] Outliner incorrectly detects 2-spaces in settings

### ISSUE THREAD

**Issue by argenos** [vslinko/obsidian-outliner#75]
**Describe the bug**
Outliner incorrectly detects 2-spaces in settings

**To Reproduce**
1. Unsure, this popped up when I updated to the latest version.

**Expected behavior**
No error message

**Screenshots**
![image](https://user-images.githubusercontent.com/5426039/114441085-397b9980-9bcb-11eb-8a17-9999ec9aebb9.png)
![image](https://user-images.githubusercontent.com/5426039/114441150-4d270000-9bcb-11eb-8cca-821fae88b6e8.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Obsidian Version: 0.11.13
- Outliner version: 1.1.0

**Additional context**
N/A

**Comment by vslinko** [comment]
@argenos Thank you for your contribution! Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.1.1
