### ISSUE TITLE
[BUG] Unable to delete bullet marker in first item of list

### ISSUE THREAD

**Issue by kritika-gupta** [vslinko/obsidian-outliner#77]
**Describe the bug**
Cannot erase the bullet point from the first item of the list to convert it into normal text. 

**To Reproduce**
1. Create a list with a minimum of two items.
2. Go to the first character of the first item.
3. Press backspace to remove the bullet mark.

**Expected behavior**
The bullet mark should be removed converting the item to normal text (and the next item becomes the first item).

**Screenshots**

https://user-images.githubusercontent.com/29776685/114502492-7c7c5200-9c49-11eb-8be3-6d5624b0b189.mov

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Obsidian Version: 0.11.13

**Comment by danieltomasz** [comment]
The behaviour is happening when the list is at the top of the file
The behaviour is happening in vanilla Obsidian too with the plugin turned off too.

**Comment by kritika-gupta** [comment]
> The behavior is happening when the list is at the top of the file
> The behavior is happening in vanilla Obsidian with the plugin turned off too.

1. The behavior happens even if the list is not at the top of the file.
2. Not true from my experiment: 
  - I created a new empty vault with all the default settings and no plugins - the behavior does not happen. The correct expected behavior happens. 
  - I added the Outliner plugin and the behavior happens. 
  - I disable the Outliner plugin and reopen the file and it is back to the behavior not happening (expected behavior happens). Reopening the file seems to be essential to bring back the vanilla Obsidian for some reason.

**Comment by vslinko** [comment]
@kritika-gupta Thank you for your contribution!

I did it on purpose because I couldn't think of a better option.

Outliner tries not to break the structure of the list, and this is important.

I can create a specific rule that behaves like you suggested, but only for cases where the element is the first in the list and has no children.
But it worries me that this is not intuitive behavior.

**Comment by kritika-gupta** [comment]
> @kritika-gupta Thank you for your contribution!
> 
> I did it on purpose because I couldn't think of a better option.
> 
> Outliner tries not to break the structure of the list, and this is important.
> 
> I can create a specific rule that behaves like you suggested, but only for cases where the element is the first in the list and has no children.
> But it worries me that this is not intuitive behavior.

I agree, it makes sense only when the element has no children. 

I came across this issue when I wanted to simply delete an item from the list and that item happened to be the first item on the list. The behavior occurred when I started to erase from the end of the item (which is how someone would probably delete an item from a list, I should have shown that in my screenshot, my bad).

**Comment by vslinko** [comment]
Fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.1.3

**Comment by kritika-gupta** [comment]
> Fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.1.3

Thanks. Your development speed is amazing. Great work on such a useful plugin!

**Comment by mathewlowry** [comment]
Not for me. I recently (re)installed Obsidian and Outliner, and the first bullet point in any list cannot be removed.

![image](https://user-images.githubusercontent.com/19875849/147825209-8815708e-3ca8-411c-9cbc-42c8d1ef9f57.png)

**Comment by vslinko** [comment]
@mathewlowry Yes, you cannot remove bullet markers when a the list item contains sub-items, because this will break the structure of the list. Please try removing the sub-items first.

**Comment by mariomui** [comment]
press ⌘ ⇧ K to delete the entire line @mathewlowry This will screw up the entire list but it will get you what you want.
![cmd-shift-k-delete-bulletline](https://github.com/vslinko/obsidian-outliner/assets/29618692/8b9ae441-5bf2-4c90-b302-876377277f65)
