### ISSUE TITLE
[BUG] relationship vertical lines not displayed

### ISSUE THREAD

**Issue by dgraziotin** [vslinko/obsidian-outliner#78]
**Describe the bug**
The plugin works in all its features excluding displaying relationship vertical lines. I am using v1.1.1 with Obsidian v0.11.13. 

All other 3rd party plugins are switched off, I am using the official theme, no snippets, no CSS. Using 4 spaces to indent.

**To Reproduce**

Using the following note:
```
- Level 1
    - Level 2
    - Level 2
        - Level 3
        - Level 3
        - Level 3
            - Level 4
            - Level 4
                - Level 5
            - Level 4
        - Level 3
    - Level 2 
- Level 1
- Level 1
    - Level 2
    - Level 2
        - Level 3
            - Level 4
    - Level 2 
- Level 1
```

I see this in the editor (same issue in the preview pane)

<img width="350" alt="Screen Shot 2021-04-13 at 12 18 07" src="https://user-images.githubusercontent.com/153179/114537292-53ac8a80-9c52-11eb-8fb7-6ec185f2fcdc.png">

**Expected behavior**

I would expect relationship lines to appear as in this Sublime Text screenshot:

<img width="245" alt="Screen Shot 2021-04-13 at 12 15 57" src="https://user-images.githubusercontent.com/153179/114537074-0f20ef00-9c52-11eb-9f19-363453d363db.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.2.2
 - Obsidian Version: v0.11.13

**Additional context**

The issue was not introduced by v1.1.1. I have never seen the lines appear, and I have been trying Outliner for about one month.

**Comment by dgraziotin** [comment]
FYI, activating the `Use tabs` Obsidian option, and redoing the list with tabs instead of spaces, fixes the issue. I would hope to be able to use spaces again though!

**Comment by danieltomasz** [comment]
I created a similar issue earlier, unfortunately there is no quick fix https://github.com/vslinko/obsidian-outliner/issues/50

**Comment by vslinko** [comment]
@dgraziotin I like to see that you found out the workaround! Please consider about voting for #57

Closing the issue for now.

**Comment by dgraziotin** [comment]
Sorry, missed #57 in my searches. That's precisely my issue and I'll vote it. Thanks for this very nice plugin, while I'm at it!
