### ISSUE TITLE
License type

### ISSUE THREAD

**Issue by JaspalSuri** [vslinko/obsidian-outliner#89]
Hi @vslinko, 

Thanks for working on this plugin; it seems pretty cool. 🙂 I was wondering what kind of license you had planned to put the code under to see if it could be used in other applications (like [Standard Notes](https://standardnotes.org)) as a user on our community Slack pointed us to this repo.

**Comment by vslinko** [comment]
Hi @JaspalSuri 

Thank you for your feedback :)

Added MIT license https://github.com/vslinko/obsidian-outliner/blob/main/LICENSE
So you can use the sources.

**Comment by JaspalSuri** [comment]
Thank you, @vslinko!
