### ISSUE TITLE
[BUG] Unable to "Select all" outside of Editor

### ISSUE THREAD

**Issue by liamcain** [vslinko/obsidian-outliner#90]
**Describe the bug**

**To Reproduce**
1. With Outliner enabled, focus the search view. 
2. Press <kbd>command</kbd><kbd>A</kbd>

**Expected behavior**
All the text in the search box should be selected

**Actual**
Nothing happens. Looks like that hotkey is bound by default. That command shouldn't fire if the cursor is outside a sourceview.

**Screenshots**

**Desktop (please complete the following information):**
 - Obsidian Version: [e.g. 22]

**Additional context**

**Comment by vslinko** [comment]
@liamcain Thank you for your contribution.

It looks like this cannot be fixed without changing the way Obisidan works with commands.
I can cancel the command if it is called from the outside, but that doesn't help because the original event remains canceled.

**Comment by vslinko** [comment]
Waiting for feedback from the Obsidian authors https://discord.com/channels/686053708261228577/707816848615407697/834454115126870086

**Comment by vslinko** [comment]
Try editorCallback https://discord.com/channels/686053708261228577/716028884885307432/838898566122438726

**Comment by vslinko** [comment]
editorCallback doesn't help — it has same issue

**Comment by vslinko** [comment]
Looks like it's better to remove the command and subscribe to original CodeMirror events.

Pros:
- Problem with search box will be solved.

Cons:
- Keystroke couldn't be changed from <kbd>Cmd</kbd><kbd>A</kbd> or <kbd>Ctrl</kbd><kbd>A</kbd>

**Comment by vslinko** [comment]
Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.1.8
