### ISSUE TITLE
[BUG] Non-numbered lists with plus signs ignored

### ISSUE THREAD

**Issue by Delta-SC** [vslinko/obsidian-outliner#91]
_This is my first time reporting a bug on Github, so please let me know if anything here is inappropriate or if you need more information!_

**Describe the bug**
The plugin ignores non-numbered lists that begin with a plus sign (+) as the list bullet. The shortcuts only apply to non-numbered lists that begin with a dash (-). 

**To Reproduce**
1. Install the plugin (applies to both manual and automatic installation as described in the developer's notes)
2. Press any of the default shortcuts to move, indent, collapse/expand lists that begin with (+) list bullet.

**Desktop (please complete the following information):**
 - OS: 10.15.7
 - Obsidian Version: v.0.11.13

**Additional context**
I know that the plugin is working properly because the shortcuts apply to numbered and non-numbered lists beginning with (-), and because the style modification is working properly. 

If there is a way to manually edit the code myself to fix this, I am happy to! My entire database uses (+) lists and I would love to make it work with this wonderful plugin!

**Comment by vslinko** [comment]
@Delta-SC Thank you for your contribution!

Should be fixed in https://github.com/vslinko/obsidian-outliner/releases/tag/1.1.5

**Comment by Delta-SC** [comment]
That was so quick!! Thank you for developing this plugin and keeping it updated for the rest of us! :D
