### ISSUE TITLE
[BUG] Outliner prevents the document from being displayed in outline view!

### ISSUE THREAD

**Issue by odysseus90210** [vslinko/obsidian-outliner#92]
**Describe the bug**
If I assign headers to bullets in a document, those should appear when I choose to "open outline" in the sidebar
However, if I open outline, nothing is displayed. 

**To Reproduce**
1. Create a document
2. Create an outline
3. Label some items with #, ##, ###, etc.
4. Choose "Open outline"

**Expected behavior**
I expect to see my document in outline form

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS 11.3
 - Obsidian Version: 0.12.0

**Additional context**

**Comment by vslinko** [comment]
@odysseus90210 Thank you for your contribution!

If I understand correctly, headers are incompatible with lists in Obsidian and I can't fix it in the plugin.

https://github.com/vslinko/obsidian-outliner/issues/18#issuecomment-809480913

Please feel free to reopen the issue If you meant something different.
