### ISSUE TITLE
[BUG] Lines don't seem to be drawn between bullet points in light or dark mode

### ISSUE THREAD

**Issue by macintacos** [vslinko/obsidian-outliner#93]
Note, I'm running a new insider build of Obsidian, so that might be causing the issue. I just wanted to report it in case others were seeing this as well.

It doesn't seem like the lines are being drawn between the bullet items when the option "Improve the style of your lists" is checked. It doesn't look like what is shown in the gif in the README. Also, it doesn't look like the "disclosure carets" are aligned properly as well. As far as I can tell it doesn't make a different when I turn off the line numbers or change the font size, and I've made sure to turn off every piece of theming that I have to make sure there wasn't something conflicting there. Not sure what's up.

## Screenshots

![image](https://user-images.githubusercontent.com/8128941/115338154-40c51900-a170-11eb-9014-3778933dfefc.png)
![image](https://user-images.githubusercontent.com/8128941/115338190-4d497180-a170-11eb-9bcc-b4689316d732.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3
 - Obsidian Version: 0.12.0

**Comment by vslinko** [comment]
@macintacos Thank you for your contribution!

Lines only work with 4-spaced tabs. Please check your Obsidian configuration.

<img width="1431" alt="Screenshot 2021-04-20 at 10 37 36" src="https://user-images.githubusercontent.com/205823/115356874-bf4ba600-a1c4-11eb-8e28-dc66f64f352a.png">

**Comment by vslinko** [comment]
Could you please create a separate issue about bad alignment of "disclosure carets" and I'll fix it.

**Comment by vslinko** [comment]
@macintacos Please close the issue if my comment was helpful.

**Comment by macintacos** [comment]
The README says:

> Styles only work well with spaces or four-space tabs.

I use spaces, and they are 4-spaced. Why does the README say it works well with spaces if it doesn't? Can this reliance on tabs be removed then? I dislike tabs 🙂

**Comment by macintacos** [comment]
Actually I just turned on the "Tabs", set the tabs to 4, and it's still not rendering the lines.

**Comment by vslinko** [comment]
Made disclaimer more clear:

> **Disclaimer:** Styles are only compatible with built-in Obsidian themes and may not be compatible with other themes. Circle bullets only work well with spaces or four-space tabs. Indentation lines only work well with four-space tabs.

Unfortunately it's mostly impossible to make it work well with spaces.

**Comment by vslinko** [comment]
> Actually I just turned on the "Tabs", set the tabs to 4, and it's still not rendering the lines.

@macintacos Changing "Tabs" setting applies only on newly created lists. Please try to create a new one.

**Comment by macintacos** [comment]
Got it, okay. Closing this out in that case.
