### ISSUE TITLE
[BUG] Disclosure carets don't seem to align nicely with bullets

### ISSUE THREAD

**Issue by macintacos** [vslinko/obsidian-outliner#95]
Was asked to create a new issue for the alignment of the disclosure carets - I've linked the same images below to demonstrate the issue.

## Screenshots

![image](https://user-images.githubusercontent.com/8128941/115338154-40c51900-a170-11eb-9014-3778933dfefc.png)
![image](https://user-images.githubusercontent.com/8128941/115338190-4d497180-a170-11eb-9bcc-b4689316d732.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3
 - Obsidian Version: 0.12.0

__Originally posted by @macintacos in https://github.com/vslinko/obsidian-outliner/issues/93__

**Comment by Nadastique** [comment]
<img width="525" alt="image" src="https://user-images.githubusercontent.com/9394790/133896595-c2f8be70-d019-4900-8d58-c4492499de08.png">
@vslinko 
and this problem here, maybe it's the same problem ;)

**Comment by seyvoue** [comment]
- I have the same problem, i record a gif bellow

![CleanShot 2021-12-24 at 14 06 51](https://user-images.githubusercontent.com/21237993/147323435-67fd0375-c4ca-4617-96f5-ccb7f4425d64.gif)

**Comment by vslinko** [comment]
@macintacos Thank you for your feedback! Should be fixed after 2.0 release. Could you please check that everything is ok?

**Comment by vslinko** [comment]
Closed due to inactivity. If you are still experiencing the problem, please create a new issue.
