### ISSUE TITLE
[FEAT] Zoom in on Heading

### ISSUE THREAD

**Issue by Weltenkreuzer** [vslinko/obsidian-outliner#99]
While zooming in on bullets works great, a nice litte addition would be the ability to zoom in on headings.

Thanks for all your effort!

**Comment by JasonAn** [comment]
same here. I am a fan of headings because outline mode will show structure more clearly

**Comment by vslinko** [comment]
Thank you for your feedback!

Looks like it's popular feature request: #97 #53 #61 

Added it into my backlog

**Comment by miguelmarcos** [comment]
I would like to add numeric outlining as well. Unless, that is, I'm doing something wrong. When I type a numeric outline and type Ctrl - . it does nothing. On non-numeric outlines it zooms in and out as expected.

Great plugin!

**Comment by vslinko** [comment]
@miguelmarcos For ordered lists I already have an issue #46 :)

**Comment by miguelmarcos** [comment]
> @miguelmarcos For ordered lists I already have an issue #46 :)

Noted, many thanks.

**Comment by santiyounger** [comment]
Perfect, yes this is what was being discussed in https://github.com/vslinko/obsidian-outliner/discussions/97 This would be an excellent feature, that would take this plugin to the next level.

**Comment by vslinko** [comment]
Hello everyone!

I made the new Obsidian Zoom plugin with headings support! Please check it out https://github.com/vslinko/obsidian-zoom

**Comment by scottsemple** [comment]
Is there a way to start the zoom from the heading level?

As it is, it seems necessary to always zoom into a bullet and then zoom out via the heading links (rather than clicking on a # directly.)

**Comment by vslinko** [comment]
@scottsemple Hi! You could move your cursor onto the heading and press <kbd>Cmd</kbd><kbd>.</kbd> or  <kbd>Ctrl</kbd><kbd>.</kbd>

**Comment by scottsemple** [comment]
Excellent! Thank you.

**Comment by showme** [comment]
Such a wonderful plugin, major thanks for creating it!
